# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/grossmj/workspace/git/gns3-gui/gns3/modules/dynamips/ui/dynamips_preferences_page.ui'
#
# Created: Mon Mar 17 21:37:06 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DynamipsPreferencesPageWidget(object):
    def setupUi(self, DynamipsPreferencesPageWidget):
        DynamipsPreferencesPageWidget.setObjectName(_fromUtf8("DynamipsPreferencesPageWidget"))
        DynamipsPreferencesPageWidget.resize(432, 508)
        self.vboxlayout = QtGui.QVBoxLayout(DynamipsPreferencesPageWidget)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.uiTabWidget = QtGui.QTabWidget(DynamipsPreferencesPageWidget)
        self.uiTabWidget.setObjectName(_fromUtf8("uiTabWidget"))
        self.uiGeneralSettingsTabWidget = QtGui.QWidget()
        self.uiGeneralSettingsTabWidget.setObjectName(_fromUtf8("uiGeneralSettingsTabWidget"))
        self.gridLayout = QtGui.QGridLayout(self.uiGeneralSettingsTabWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.uiDynamipsPathLabel = QtGui.QLabel(self.uiGeneralSettingsTabWidget)
        self.uiDynamipsPathLabel.setObjectName(_fromUtf8("uiDynamipsPathLabel"))
        self.gridLayout.addWidget(self.uiDynamipsPathLabel, 0, 0, 1, 1)
        self.uiBaseHypervisorPortLabel = QtGui.QLabel(self.uiGeneralSettingsTabWidget)
        self.uiBaseHypervisorPortLabel.setObjectName(_fromUtf8("uiBaseHypervisorPortLabel"))
        self.gridLayout.addWidget(self.uiBaseHypervisorPortLabel, 2, 0, 1, 1)
        self.uiBaseConsolePortLabel = QtGui.QLabel(self.uiGeneralSettingsTabWidget)
        self.uiBaseConsolePortLabel.setObjectName(_fromUtf8("uiBaseConsolePortLabel"))
        self.gridLayout.addWidget(self.uiBaseConsolePortLabel, 4, 0, 1, 1)
        self.uiBaseAuxPortLabel = QtGui.QLabel(self.uiGeneralSettingsTabWidget)
        self.uiBaseAuxPortLabel.setObjectName(_fromUtf8("uiBaseAuxPortLabel"))
        self.gridLayout.addWidget(self.uiBaseAuxPortLabel, 6, 0, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.uiTestSettingsPushButton = QtGui.QPushButton(self.uiGeneralSettingsTabWidget)
        self.uiTestSettingsPushButton.setObjectName(_fromUtf8("uiTestSettingsPushButton"))
        self.horizontalLayout_2.addWidget(self.uiTestSettingsPushButton)
        self.uiRestoreDefaultsPushButton = QtGui.QPushButton(self.uiGeneralSettingsTabWidget)
        self.uiRestoreDefaultsPushButton.setObjectName(_fromUtf8("uiRestoreDefaultsPushButton"))
        self.horizontalLayout_2.addWidget(self.uiRestoreDefaultsPushButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 8, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(164, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 8, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(390, 193, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 9, 0, 1, 2)
        self.uiBaseAuxPortSpinBox = QtGui.QSpinBox(self.uiGeneralSettingsTabWidget)
        self.uiBaseAuxPortSpinBox.setSuffix(_fromUtf8(" TCP"))
        self.uiBaseAuxPortSpinBox.setMaximum(65535)
        self.uiBaseAuxPortSpinBox.setProperty("value", 2501)
        self.uiBaseAuxPortSpinBox.setObjectName(_fromUtf8("uiBaseAuxPortSpinBox"))
        self.gridLayout.addWidget(self.uiBaseAuxPortSpinBox, 7, 0, 1, 2)
        self.uiBaseConsolePortSpinBox = QtGui.QSpinBox(self.uiGeneralSettingsTabWidget)
        self.uiBaseConsolePortSpinBox.setSuffix(_fromUtf8(" TCP"))
        self.uiBaseConsolePortSpinBox.setMaximum(65535)
        self.uiBaseConsolePortSpinBox.setProperty("value", 2001)
        self.uiBaseConsolePortSpinBox.setObjectName(_fromUtf8("uiBaseConsolePortSpinBox"))
        self.gridLayout.addWidget(self.uiBaseConsolePortSpinBox, 5, 0, 1, 2)
        self.uiBaseHypervisorPortSpinBox = QtGui.QSpinBox(self.uiGeneralSettingsTabWidget)
        self.uiBaseHypervisorPortSpinBox.setSuffix(_fromUtf8(" TCP"))
        self.uiBaseHypervisorPortSpinBox.setMaximum(65535)
        self.uiBaseHypervisorPortSpinBox.setProperty("value", 7200)
        self.uiBaseHypervisorPortSpinBox.setObjectName(_fromUtf8("uiBaseHypervisorPortSpinBox"))
        self.gridLayout.addWidget(self.uiBaseHypervisorPortSpinBox, 3, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uiDynamipsPathLineEdit = QtGui.QLineEdit(self.uiGeneralSettingsTabWidget)
        self.uiDynamipsPathLineEdit.setObjectName(_fromUtf8("uiDynamipsPathLineEdit"))
        self.horizontalLayout.addWidget(self.uiDynamipsPathLineEdit)
        self.uiDynamipsPathToolButton = QtGui.QToolButton(self.uiGeneralSettingsTabWidget)
        self.uiDynamipsPathToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.uiDynamipsPathToolButton.setObjectName(_fromUtf8("uiDynamipsPathToolButton"))
        self.horizontalLayout.addWidget(self.uiDynamipsPathToolButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.uiTabWidget.addTab(self.uiGeneralSettingsTabWidget, _fromUtf8(""))
        self.uiServerSettingsTabWidget = QtGui.QWidget()
        self.uiServerSettingsTabWidget.setObjectName(_fromUtf8("uiServerSettingsTabWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.uiServerSettingsTabWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.uiUseLocalServercheckBox = QtGui.QCheckBox(self.uiServerSettingsTabWidget)
        self.uiUseLocalServercheckBox.setChecked(True)
        self.uiUseLocalServercheckBox.setObjectName(_fromUtf8("uiUseLocalServercheckBox"))
        self.gridLayout_2.addWidget(self.uiUseLocalServercheckBox, 0, 0, 1, 1)
        self.uiRemoteServersGroupBox = QtGui.QGroupBox(self.uiServerSettingsTabWidget)
        self.uiRemoteServersGroupBox.setObjectName(_fromUtf8("uiRemoteServersGroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.uiRemoteServersGroupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.uiRemoteServersTreeWidget = QtGui.QTreeWidget(self.uiRemoteServersGroupBox)
        self.uiRemoteServersTreeWidget.setEnabled(False)
        self.uiRemoteServersTreeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.uiRemoteServersTreeWidget.setObjectName(_fromUtf8("uiRemoteServersTreeWidget"))
        self.horizontalLayout_3.addWidget(self.uiRemoteServersTreeWidget)
        self.gridLayout_2.addWidget(self.uiRemoteServersGroupBox, 1, 0, 1, 1)
        self.uiTabWidget.addTab(self.uiServerSettingsTabWidget, _fromUtf8(""))
        self.uiAdvancedSettingsTabWidget = QtGui.QWidget()
        self.uiAdvancedSettingsTabWidget.setObjectName(_fromUtf8("uiAdvancedSettingsTabWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.uiAdvancedSettingsTabWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.uiHypervisorAllocationGroupBox = QtGui.QGroupBox(self.uiAdvancedSettingsTabWidget)
        self.uiHypervisorAllocationGroupBox.setObjectName(_fromUtf8("uiHypervisorAllocationGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.uiHypervisorAllocationGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.uiAllocateHypervisorPerDeviceCheckBox = QtGui.QCheckBox(self.uiHypervisorAllocationGroupBox)
        self.uiAllocateHypervisorPerDeviceCheckBox.setChecked(True)
        self.uiAllocateHypervisorPerDeviceCheckBox.setObjectName(_fromUtf8("uiAllocateHypervisorPerDeviceCheckBox"))
        self.verticalLayout_2.addWidget(self.uiAllocateHypervisorPerDeviceCheckBox)
        self.uiMemoryUsageLimitPerHypervisorLabel = QtGui.QLabel(self.uiHypervisorAllocationGroupBox)
        self.uiMemoryUsageLimitPerHypervisorLabel.setObjectName(_fromUtf8("uiMemoryUsageLimitPerHypervisorLabel"))
        self.verticalLayout_2.addWidget(self.uiMemoryUsageLimitPerHypervisorLabel)
        self.uiMemoryUsageLimitPerHypervisorSpinBox = QtGui.QSpinBox(self.uiHypervisorAllocationGroupBox)
        self.uiMemoryUsageLimitPerHypervisorSpinBox.setEnabled(False)
        self.uiMemoryUsageLimitPerHypervisorSpinBox.setMaximum(1000000)
        self.uiMemoryUsageLimitPerHypervisorSpinBox.setSingleStep(128)
        self.uiMemoryUsageLimitPerHypervisorSpinBox.setProperty("value", 512)
        self.uiMemoryUsageLimitPerHypervisorSpinBox.setObjectName(_fromUtf8("uiMemoryUsageLimitPerHypervisorSpinBox"))
        self.verticalLayout_2.addWidget(self.uiMemoryUsageLimitPerHypervisorSpinBox)
        self.uiAllocateHypervisorPerIOSCheckBox = QtGui.QCheckBox(self.uiHypervisorAllocationGroupBox)
        self.uiAllocateHypervisorPerIOSCheckBox.setEnabled(False)
        self.uiAllocateHypervisorPerIOSCheckBox.setChecked(True)
        self.uiAllocateHypervisorPerIOSCheckBox.setObjectName(_fromUtf8("uiAllocateHypervisorPerIOSCheckBox"))
        self.verticalLayout_2.addWidget(self.uiAllocateHypervisorPerIOSCheckBox)
        self.verticalLayout_4.addWidget(self.uiHypervisorAllocationGroupBox)
        self.uiUDPTunnelingGroupBox = QtGui.QGroupBox(self.uiAdvancedSettingsTabWidget)
        self.uiUDPTunnelingGroupBox.setObjectName(_fromUtf8("uiUDPTunnelingGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.uiUDPTunnelingGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.uiBaseUDPPortLabel = QtGui.QLabel(self.uiUDPTunnelingGroupBox)
        self.uiBaseUDPPortLabel.setObjectName(_fromUtf8("uiBaseUDPPortLabel"))
        self.verticalLayout_3.addWidget(self.uiBaseUDPPortLabel)
        self.uiBaseUDPPortSpinBox = QtGui.QSpinBox(self.uiUDPTunnelingGroupBox)
        self.uiBaseUDPPortSpinBox.setSuffix(_fromUtf8(" UDP"))
        self.uiBaseUDPPortSpinBox.setMaximum(65535)
        self.uiBaseUDPPortSpinBox.setProperty("value", 10001)
        self.uiBaseUDPPortSpinBox.setObjectName(_fromUtf8("uiBaseUDPPortSpinBox"))
        self.verticalLayout_3.addWidget(self.uiBaseUDPPortSpinBox)
        self.uiBaseUDPPortIncrementationLabel = QtGui.QLabel(self.uiUDPTunnelingGroupBox)
        self.uiBaseUDPPortIncrementationLabel.setObjectName(_fromUtf8("uiBaseUDPPortIncrementationLabel"))
        self.verticalLayout_3.addWidget(self.uiBaseUDPPortIncrementationLabel)
        self.uiBaseUDPPortIncrementationSpinBox = QtGui.QSpinBox(self.uiUDPTunnelingGroupBox)
        self.uiBaseUDPPortIncrementationSpinBox.setMaximum(100000)
        self.uiBaseUDPPortIncrementationSpinBox.setSingleStep(10)
        self.uiBaseUDPPortIncrementationSpinBox.setProperty("value", 100)
        self.uiBaseUDPPortIncrementationSpinBox.setObjectName(_fromUtf8("uiBaseUDPPortIncrementationSpinBox"))
        self.verticalLayout_3.addWidget(self.uiBaseUDPPortIncrementationSpinBox)
        self.verticalLayout_4.addWidget(self.uiUDPTunnelingGroupBox)
        self.uiMemoryUsageOptimisationGroupBox = QtGui.QGroupBox(self.uiAdvancedSettingsTabWidget)
        self.uiMemoryUsageOptimisationGroupBox.setObjectName(_fromUtf8("uiMemoryUsageOptimisationGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.uiMemoryUsageOptimisationGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.uiGhostIOSSupportCheckBox = QtGui.QCheckBox(self.uiMemoryUsageOptimisationGroupBox)
        self.uiGhostIOSSupportCheckBox.setChecked(True)
        self.uiGhostIOSSupportCheckBox.setObjectName(_fromUtf8("uiGhostIOSSupportCheckBox"))
        self.verticalLayout.addWidget(self.uiGhostIOSSupportCheckBox)
        self.uiMmapSupportCheckBox = QtGui.QCheckBox(self.uiMemoryUsageOptimisationGroupBox)
        self.uiMmapSupportCheckBox.setChecked(True)
        self.uiMmapSupportCheckBox.setObjectName(_fromUtf8("uiMmapSupportCheckBox"))
        self.verticalLayout.addWidget(self.uiMmapSupportCheckBox)
        self.uiJITSharingSupportCheckBox = QtGui.QCheckBox(self.uiMemoryUsageOptimisationGroupBox)
        self.uiJITSharingSupportCheckBox.setChecked(True)
        self.uiJITSharingSupportCheckBox.setObjectName(_fromUtf8("uiJITSharingSupportCheckBox"))
        self.verticalLayout.addWidget(self.uiJITSharingSupportCheckBox)
        self.uiSparseMemorySupportCheckBox = QtGui.QCheckBox(self.uiMemoryUsageOptimisationGroupBox)
        self.uiSparseMemorySupportCheckBox.setChecked(False)
        self.uiSparseMemorySupportCheckBox.setObjectName(_fromUtf8("uiSparseMemorySupportCheckBox"))
        self.verticalLayout.addWidget(self.uiSparseMemorySupportCheckBox)
        self.verticalLayout_4.addWidget(self.uiMemoryUsageOptimisationGroupBox)
        spacerItem2 = QtGui.QSpacerItem(390, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.uiTabWidget.addTab(self.uiAdvancedSettingsTabWidget, _fromUtf8(""))
        self.vboxlayout.addWidget(self.uiTabWidget)

        self.retranslateUi(DynamipsPreferencesPageWidget)
        self.uiTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DynamipsPreferencesPageWidget)
        DynamipsPreferencesPageWidget.setTabOrder(self.uiTabWidget, self.uiDynamipsPathLineEdit)
        DynamipsPreferencesPageWidget.setTabOrder(self.uiDynamipsPathLineEdit, self.uiDynamipsPathToolButton)
        DynamipsPreferencesPageWidget.setTabOrder(self.uiDynamipsPathToolButton, self.uiBaseHypervisorPortSpinBox)
        DynamipsPreferencesPageWidget.setTabOrder(self.uiBaseHypervisorPortSpinBox, self.uiBaseConsolePortSpinBox)
        DynamipsPreferencesPageWidget.setTabOrder(self.uiBaseConsolePortSpinBox, self.uiBaseAuxPortSpinBox)
        DynamipsPreferencesPageWidget.setTabOrder(self.uiBaseAuxPortSpinBox, self.uiAllocateHypervisorPerDeviceCheckBox)
        DynamipsPreferencesPageWidget.setTabOrder(self.uiAllocateHypervisorPerDeviceCheckBox, self.uiMemoryUsageLimitPerHypervisorSpinBox)
        DynamipsPreferencesPageWidget.setTabOrder(self.uiMemoryUsageLimitPerHypervisorSpinBox, self.uiAllocateHypervisorPerIOSCheckBox)
        DynamipsPreferencesPageWidget.setTabOrder(self.uiAllocateHypervisorPerIOSCheckBox, self.uiBaseUDPPortSpinBox)
        DynamipsPreferencesPageWidget.setTabOrder(self.uiBaseUDPPortSpinBox, self.uiBaseUDPPortIncrementationSpinBox)
        DynamipsPreferencesPageWidget.setTabOrder(self.uiBaseUDPPortIncrementationSpinBox, self.uiGhostIOSSupportCheckBox)
        DynamipsPreferencesPageWidget.setTabOrder(self.uiGhostIOSSupportCheckBox, self.uiMmapSupportCheckBox)
        DynamipsPreferencesPageWidget.setTabOrder(self.uiMmapSupportCheckBox, self.uiJITSharingSupportCheckBox)
        DynamipsPreferencesPageWidget.setTabOrder(self.uiJITSharingSupportCheckBox, self.uiSparseMemorySupportCheckBox)

    def retranslateUi(self, DynamipsPreferencesPageWidget):
        DynamipsPreferencesPageWidget.setWindowTitle(_translate("DynamipsPreferencesPageWidget", "Dynamips", None))
        self.uiDynamipsPathLabel.setText(_translate("DynamipsPreferencesPageWidget", "Path to Dynamips:", None))
        self.uiBaseHypervisorPortLabel.setText(_translate("DynamipsPreferencesPageWidget", "Base port for hypervisors:", None))
        self.uiBaseConsolePortLabel.setText(_translate("DynamipsPreferencesPageWidget", "Base console port for routers:", None))
        self.uiBaseAuxPortLabel.setText(_translate("DynamipsPreferencesPageWidget", "Base auxiliary console port for routers:", None))
        self.uiTestSettingsPushButton.setText(_translate("DynamipsPreferencesPageWidget", "Test settings", None))
        self.uiRestoreDefaultsPushButton.setText(_translate("DynamipsPreferencesPageWidget", "Restore defaults", None))
        self.uiDynamipsPathToolButton.setText(_translate("DynamipsPreferencesPageWidget", "...", None))
        self.uiTabWidget.setTabText(self.uiTabWidget.indexOf(self.uiGeneralSettingsTabWidget), _translate("DynamipsPreferencesPageWidget", "General settings", None))
        self.uiUseLocalServercheckBox.setText(_translate("DynamipsPreferencesPageWidget", "Use the local server", None))
        self.uiRemoteServersGroupBox.setTitle(_translate("DynamipsPreferencesPageWidget", "Remote servers", None))
        self.uiRemoteServersTreeWidget.headerItem().setText(0, _translate("DynamipsPreferencesPageWidget", "Host", None))
        self.uiRemoteServersTreeWidget.headerItem().setText(1, _translate("DynamipsPreferencesPageWidget", "Port", None))
        self.uiTabWidget.setTabText(self.uiTabWidget.indexOf(self.uiServerSettingsTabWidget), _translate("DynamipsPreferencesPageWidget", "Server settings", None))
        self.uiHypervisorAllocationGroupBox.setTitle(_translate("DynamipsPreferencesPageWidget", "Hypervisor allocation", None))
        self.uiAllocateHypervisorPerDeviceCheckBox.setText(_translate("DynamipsPreferencesPageWidget", "Allocate a new hypervisor for each device", None))
        self.uiMemoryUsageLimitPerHypervisorLabel.setText(_translate("DynamipsPreferencesPageWidget", "Memory usage limit per hypervisor:", None))
        self.uiMemoryUsageLimitPerHypervisorSpinBox.setSuffix(_translate("DynamipsPreferencesPageWidget", " MiB", None))
        self.uiAllocateHypervisorPerIOSCheckBox.setText(_translate("DynamipsPreferencesPageWidget", "Allocate a new hypervisor per IOS image", None))
        self.uiUDPTunnelingGroupBox.setTitle(_translate("DynamipsPreferencesPageWidget", "UDP tunneling", None))
        self.uiBaseUDPPortLabel.setText(_translate("DynamipsPreferencesPageWidget", " Base UDP port:", None))
        self.uiBaseUDPPortIncrementationLabel.setText(_translate("DynamipsPreferencesPageWidget", "UDP incrementation per hypervisor:", None))
        self.uiMemoryUsageOptimisationGroupBox.setTitle(_translate("DynamipsPreferencesPageWidget", "Memory usage optimisation", None))
        self.uiGhostIOSSupportCheckBox.setText(_translate("DynamipsPreferencesPageWidget", "Enable ghost IOS support", None))
        self.uiMmapSupportCheckBox.setText(_translate("DynamipsPreferencesPageWidget", "Enable mmap support", None))
        self.uiJITSharingSupportCheckBox.setText(_translate("DynamipsPreferencesPageWidget", "Enable JIT sharing support", None))
        self.uiSparseMemorySupportCheckBox.setText(_translate("DynamipsPreferencesPageWidget", "Enable sparse memory support", None))
        self.uiTabWidget.setTabText(self.uiTabWidget.indexOf(self.uiAdvancedSettingsTabWidget), _translate("DynamipsPreferencesPageWidget", "Advanced settings", None))

