# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/grossmj/workspace/git/gns3-gui/gns3/modules/dynamips/ui/router_configuration_page.ui'
#
# Created: Tue Feb  4 22:59:03 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_routerConfigPageWidget(object):
    def setupUi(self, routerConfigPageWidget):
        routerConfigPageWidget.setObjectName(_fromUtf8("routerConfigPageWidget"))
        routerConfigPageWidget.resize(439, 480)
        self.vboxlayout = QtGui.QVBoxLayout(routerConfigPageWidget)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.uiTabWidget = QtGui.QTabWidget(routerConfigPageWidget)
        self.uiTabWidget.setObjectName(_fromUtf8("uiTabWidget"))
        self.uiGeneralTabWidget = QtGui.QWidget()
        self.uiGeneralTabWidget.setObjectName(_fromUtf8("uiGeneralTabWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.uiGeneralTabWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.uiNameLabel = QtGui.QLabel(self.uiGeneralTabWidget)
        self.uiNameLabel.setObjectName(_fromUtf8("uiNameLabel"))
        self.gridLayout_2.addWidget(self.uiNameLabel, 0, 0, 1, 1)
        self.uiNameLineEdit = QtGui.QLineEdit(self.uiGeneralTabWidget)
        self.uiNameLineEdit.setObjectName(_fromUtf8("uiNameLineEdit"))
        self.gridLayout_2.addWidget(self.uiNameLineEdit, 0, 2, 1, 1)
        self.uiConsolePortLabel = QtGui.QLabel(self.uiGeneralTabWidget)
        self.uiConsolePortLabel.setObjectName(_fromUtf8("uiConsolePortLabel"))
        self.gridLayout_2.addWidget(self.uiConsolePortLabel, 1, 0, 1, 1)
        self.uiConsolePortSpinBox = QtGui.QSpinBox(self.uiGeneralTabWidget)
        self.uiConsolePortSpinBox.setMaximum(65535)
        self.uiConsolePortSpinBox.setObjectName(_fromUtf8("uiConsolePortSpinBox"))
        self.gridLayout_2.addWidget(self.uiConsolePortSpinBox, 1, 2, 1, 1)
        self.uiAuxPortLabel = QtGui.QLabel(self.uiGeneralTabWidget)
        self.uiAuxPortLabel.setObjectName(_fromUtf8("uiAuxPortLabel"))
        self.gridLayout_2.addWidget(self.uiAuxPortLabel, 2, 0, 1, 2)
        self.uiAuxPortSpinBox = QtGui.QSpinBox(self.uiGeneralTabWidget)
        self.uiAuxPortSpinBox.setMaximum(65535)
        self.uiAuxPortSpinBox.setObjectName(_fromUtf8("uiAuxPortSpinBox"))
        self.gridLayout_2.addWidget(self.uiAuxPortSpinBox, 2, 2, 1, 1)
        self.uiPlatformLabel = QtGui.QLabel(self.uiGeneralTabWidget)
        self.uiPlatformLabel.setObjectName(_fromUtf8("uiPlatformLabel"))
        self.gridLayout_2.addWidget(self.uiPlatformLabel, 3, 0, 1, 1)
        self.uiIOSImageLabel = QtGui.QLabel(self.uiGeneralTabWidget)
        self.uiIOSImageLabel.setObjectName(_fromUtf8("uiIOSImageLabel"))
        self.gridLayout_2.addWidget(self.uiIOSImageLabel, 4, 0, 1, 1)
        self.uiStartupConfigLabel = QtGui.QLabel(self.uiGeneralTabWidget)
        self.uiStartupConfigLabel.setObjectName(_fromUtf8("uiStartupConfigLabel"))
        self.gridLayout_2.addWidget(self.uiStartupConfigLabel, 5, 0, 1, 1)
        self.uiStartupConfigTextLabel = QtGui.QLabel(self.uiGeneralTabWidget)
        self.uiStartupConfigTextLabel.setText(_fromUtf8(""))
        self.uiStartupConfigTextLabel.setObjectName(_fromUtf8("uiStartupConfigTextLabel"))
        self.gridLayout_2.addWidget(self.uiStartupConfigTextLabel, 5, 2, 1, 1)
        self.uiMidplaneLabel = QtGui.QLabel(self.uiGeneralTabWidget)
        self.uiMidplaneLabel.setObjectName(_fromUtf8("uiMidplaneLabel"))
        self.gridLayout_2.addWidget(self.uiMidplaneLabel, 6, 0, 1, 1)
        self.uiMidplaneComboBox = QtGui.QComboBox(self.uiGeneralTabWidget)
        self.uiMidplaneComboBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiMidplaneComboBox.sizePolicy().hasHeightForWidth())
        self.uiMidplaneComboBox.setSizePolicy(sizePolicy)
        self.uiMidplaneComboBox.setObjectName(_fromUtf8("uiMidplaneComboBox"))
        self.gridLayout_2.addWidget(self.uiMidplaneComboBox, 6, 1, 1, 2)
        self.uiNPELabel = QtGui.QLabel(self.uiGeneralTabWidget)
        self.uiNPELabel.setObjectName(_fromUtf8("uiNPELabel"))
        self.gridLayout_2.addWidget(self.uiNPELabel, 7, 0, 1, 1)
        self.uiNPEComboBox = QtGui.QComboBox(self.uiGeneralTabWidget)
        self.uiNPEComboBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiNPEComboBox.sizePolicy().hasHeightForWidth())
        self.uiNPEComboBox.setSizePolicy(sizePolicy)
        self.uiNPEComboBox.setObjectName(_fromUtf8("uiNPEComboBox"))
        self.gridLayout_2.addWidget(self.uiNPEComboBox, 7, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(263, 151, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 8, 1, 1, 2)
        self.uiPlatformTextLabel = QtGui.QLabel(self.uiGeneralTabWidget)
        self.uiPlatformTextLabel.setText(_fromUtf8(""))
        self.uiPlatformTextLabel.setObjectName(_fromUtf8("uiPlatformTextLabel"))
        self.gridLayout_2.addWidget(self.uiPlatformTextLabel, 3, 2, 1, 1)
        self.uiIOSImageTextLabel = QtGui.QLabel(self.uiGeneralTabWidget)
        self.uiIOSImageTextLabel.setText(_fromUtf8(""))
        self.uiIOSImageTextLabel.setObjectName(_fromUtf8("uiIOSImageTextLabel"))
        self.gridLayout_2.addWidget(self.uiIOSImageTextLabel, 4, 2, 1, 1)
        self.uiTabWidget.addTab(self.uiGeneralTabWidget, _fromUtf8(""))
        self.uiMemoriesTabWidget = QtGui.QWidget()
        self.uiMemoriesTabWidget.setObjectName(_fromUtf8("uiMemoriesTabWidget"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.uiMemoriesTabWidget)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.uiMemoriesGroupBox = QtGui.QGroupBox(self.uiMemoriesTabWidget)
        self.uiMemoriesGroupBox.setObjectName(_fromUtf8("uiMemoriesGroupBox"))
        self.gridlayout = QtGui.QGridLayout(self.uiMemoriesGroupBox)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.uiRamLabel = QtGui.QLabel(self.uiMemoriesGroupBox)
        self.uiRamLabel.setObjectName(_fromUtf8("uiRamLabel"))
        self.gridlayout.addWidget(self.uiRamLabel, 0, 0, 1, 1)
        self.uiRamSpinBox = QtGui.QSpinBox(self.uiMemoriesGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiRamSpinBox.sizePolicy().hasHeightForWidth())
        self.uiRamSpinBox.setSizePolicy(sizePolicy)
        self.uiRamSpinBox.setMaximum(4096)
        self.uiRamSpinBox.setSingleStep(4)
        self.uiRamSpinBox.setProperty("value", 128)
        self.uiRamSpinBox.setObjectName(_fromUtf8("uiRamSpinBox"))
        self.gridlayout.addWidget(self.uiRamSpinBox, 0, 1, 1, 1)
        self.uiNvramLabel = QtGui.QLabel(self.uiMemoriesGroupBox)
        self.uiNvramLabel.setObjectName(_fromUtf8("uiNvramLabel"))
        self.gridlayout.addWidget(self.uiNvramLabel, 1, 0, 1, 1)
        self.uiNvramSpinBox = QtGui.QSpinBox(self.uiMemoriesGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiNvramSpinBox.sizePolicy().hasHeightForWidth())
        self.uiNvramSpinBox.setSizePolicy(sizePolicy)
        self.uiNvramSpinBox.setMaximum(4096)
        self.uiNvramSpinBox.setSingleStep(4)
        self.uiNvramSpinBox.setProperty("value", 128)
        self.uiNvramSpinBox.setObjectName(_fromUtf8("uiNvramSpinBox"))
        self.gridlayout.addWidget(self.uiNvramSpinBox, 1, 1, 1, 1)
        self.vboxlayout1.addWidget(self.uiMemoriesGroupBox)
        self.uiDisksGroupBox = QtGui.QGroupBox(self.uiMemoriesTabWidget)
        self.uiDisksGroupBox.setObjectName(_fromUtf8("uiDisksGroupBox"))
        self.gridlayout1 = QtGui.QGridLayout(self.uiDisksGroupBox)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.uiDisk0Label = QtGui.QLabel(self.uiDisksGroupBox)
        self.uiDisk0Label.setObjectName(_fromUtf8("uiDisk0Label"))
        self.gridlayout1.addWidget(self.uiDisk0Label, 0, 0, 1, 1)
        self.uiDisk0SpinBox = QtGui.QSpinBox(self.uiDisksGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiDisk0SpinBox.sizePolicy().hasHeightForWidth())
        self.uiDisk0SpinBox.setSizePolicy(sizePolicy)
        self.uiDisk0SpinBox.setMaximum(99999)
        self.uiDisk0SpinBox.setSingleStep(4)
        self.uiDisk0SpinBox.setObjectName(_fromUtf8("uiDisk0SpinBox"))
        self.gridlayout1.addWidget(self.uiDisk0SpinBox, 0, 1, 1, 1)
        self.uiDisk1Label = QtGui.QLabel(self.uiDisksGroupBox)
        self.uiDisk1Label.setObjectName(_fromUtf8("uiDisk1Label"))
        self.gridlayout1.addWidget(self.uiDisk1Label, 1, 0, 1, 1)
        self.uiDisk1SpinBox = QtGui.QSpinBox(self.uiDisksGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiDisk1SpinBox.sizePolicy().hasHeightForWidth())
        self.uiDisk1SpinBox.setSizePolicy(sizePolicy)
        self.uiDisk1SpinBox.setMaximum(99999)
        self.uiDisk1SpinBox.setSingleStep(4)
        self.uiDisk1SpinBox.setObjectName(_fromUtf8("uiDisk1SpinBox"))
        self.gridlayout1.addWidget(self.uiDisk1SpinBox, 1, 1, 1, 1)
        self.vboxlayout1.addWidget(self.uiDisksGroupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem1)
        self.uiTabWidget.addTab(self.uiMemoriesTabWidget, _fromUtf8(""))
        self.uiSlotsTabWidget = QtGui.QWidget()
        self.uiSlotsTabWidget.setObjectName(_fromUtf8("uiSlotsTabWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.uiSlotsTabWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.uiAdaptersGroupBox = QtGui.QGroupBox(self.uiSlotsTabWidget)
        self.uiAdaptersGroupBox.setObjectName(_fromUtf8("uiAdaptersGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.uiAdaptersGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.uiSlot1comboBox = QtGui.QComboBox(self.uiAdaptersGroupBox)
        self.uiSlot1comboBox.setObjectName(_fromUtf8("uiSlot1comboBox"))
        self.gridLayout.addWidget(self.uiSlot1comboBox, 1, 1, 1, 1)
        self.uiSlot0Label = QtGui.QLabel(self.uiAdaptersGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSlot0Label.sizePolicy().hasHeightForWidth())
        self.uiSlot0Label.setSizePolicy(sizePolicy)
        self.uiSlot0Label.setObjectName(_fromUtf8("uiSlot0Label"))
        self.gridLayout.addWidget(self.uiSlot0Label, 0, 0, 1, 1)
        self.uiSlot0comboBox = QtGui.QComboBox(self.uiAdaptersGroupBox)
        self.uiSlot0comboBox.setObjectName(_fromUtf8("uiSlot0comboBox"))
        self.gridLayout.addWidget(self.uiSlot0comboBox, 0, 1, 1, 1)
        self.uiSlot1Label = QtGui.QLabel(self.uiAdaptersGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSlot1Label.sizePolicy().hasHeightForWidth())
        self.uiSlot1Label.setSizePolicy(sizePolicy)
        self.uiSlot1Label.setObjectName(_fromUtf8("uiSlot1Label"))
        self.gridLayout.addWidget(self.uiSlot1Label, 1, 0, 1, 1)
        self.uiSlot2Label = QtGui.QLabel(self.uiAdaptersGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSlot2Label.sizePolicy().hasHeightForWidth())
        self.uiSlot2Label.setSizePolicy(sizePolicy)
        self.uiSlot2Label.setObjectName(_fromUtf8("uiSlot2Label"))
        self.gridLayout.addWidget(self.uiSlot2Label, 2, 0, 1, 1)
        self.uiSlot2comboBox = QtGui.QComboBox(self.uiAdaptersGroupBox)
        self.uiSlot2comboBox.setObjectName(_fromUtf8("uiSlot2comboBox"))
        self.gridLayout.addWidget(self.uiSlot2comboBox, 2, 1, 1, 1)
        self.uiSlot3Label = QtGui.QLabel(self.uiAdaptersGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSlot3Label.sizePolicy().hasHeightForWidth())
        self.uiSlot3Label.setSizePolicy(sizePolicy)
        self.uiSlot3Label.setObjectName(_fromUtf8("uiSlot3Label"))
        self.gridLayout.addWidget(self.uiSlot3Label, 3, 0, 1, 1)
        self.uiSlot3comboBox = QtGui.QComboBox(self.uiAdaptersGroupBox)
        self.uiSlot3comboBox.setObjectName(_fromUtf8("uiSlot3comboBox"))
        self.gridLayout.addWidget(self.uiSlot3comboBox, 3, 1, 1, 1)
        self.uiSlot4Label = QtGui.QLabel(self.uiAdaptersGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSlot4Label.sizePolicy().hasHeightForWidth())
        self.uiSlot4Label.setSizePolicy(sizePolicy)
        self.uiSlot4Label.setObjectName(_fromUtf8("uiSlot4Label"))
        self.gridLayout.addWidget(self.uiSlot4Label, 4, 0, 1, 1)
        self.uiSlot4comboBox = QtGui.QComboBox(self.uiAdaptersGroupBox)
        self.uiSlot4comboBox.setObjectName(_fromUtf8("uiSlot4comboBox"))
        self.gridLayout.addWidget(self.uiSlot4comboBox, 4, 1, 1, 1)
        self.uiSlot5Label = QtGui.QLabel(self.uiAdaptersGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSlot5Label.sizePolicy().hasHeightForWidth())
        self.uiSlot5Label.setSizePolicy(sizePolicy)
        self.uiSlot5Label.setObjectName(_fromUtf8("uiSlot5Label"))
        self.gridLayout.addWidget(self.uiSlot5Label, 5, 0, 1, 1)
        self.uiSlot5comboBox = QtGui.QComboBox(self.uiAdaptersGroupBox)
        self.uiSlot5comboBox.setObjectName(_fromUtf8("uiSlot5comboBox"))
        self.gridLayout.addWidget(self.uiSlot5comboBox, 5, 1, 1, 1)
        self.uiSlot6Label = QtGui.QLabel(self.uiAdaptersGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSlot6Label.sizePolicy().hasHeightForWidth())
        self.uiSlot6Label.setSizePolicy(sizePolicy)
        self.uiSlot6Label.setObjectName(_fromUtf8("uiSlot6Label"))
        self.gridLayout.addWidget(self.uiSlot6Label, 6, 0, 1, 1)
        self.uiSlot6comboBox = QtGui.QComboBox(self.uiAdaptersGroupBox)
        self.uiSlot6comboBox.setObjectName(_fromUtf8("uiSlot6comboBox"))
        self.gridLayout.addWidget(self.uiSlot6comboBox, 6, 1, 1, 1)
        self.verticalLayout.addWidget(self.uiAdaptersGroupBox)
        self.uiWicsGroupBox = QtGui.QGroupBox(self.uiSlotsTabWidget)
        self.uiWicsGroupBox.setObjectName(_fromUtf8("uiWicsGroupBox"))
        self.gridlayout2 = QtGui.QGridLayout(self.uiWicsGroupBox)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.uiWic0Label = QtGui.QLabel(self.uiWicsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiWic0Label.sizePolicy().hasHeightForWidth())
        self.uiWic0Label.setSizePolicy(sizePolicy)
        self.uiWic0Label.setObjectName(_fromUtf8("uiWic0Label"))
        self.gridlayout2.addWidget(self.uiWic0Label, 0, 0, 1, 1)
        self.uiWic0comboBox = QtGui.QComboBox(self.uiWicsGroupBox)
        self.uiWic0comboBox.setObjectName(_fromUtf8("uiWic0comboBox"))
        self.gridlayout2.addWidget(self.uiWic0comboBox, 0, 1, 1, 1)
        self.uiWic1Label = QtGui.QLabel(self.uiWicsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiWic1Label.sizePolicy().hasHeightForWidth())
        self.uiWic1Label.setSizePolicy(sizePolicy)
        self.uiWic1Label.setObjectName(_fromUtf8("uiWic1Label"))
        self.gridlayout2.addWidget(self.uiWic1Label, 1, 0, 1, 1)
        self.uiWic1comboBox = QtGui.QComboBox(self.uiWicsGroupBox)
        self.uiWic1comboBox.setObjectName(_fromUtf8("uiWic1comboBox"))
        self.gridlayout2.addWidget(self.uiWic1comboBox, 1, 1, 1, 1)
        self.uiWic2Label = QtGui.QLabel(self.uiWicsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiWic2Label.sizePolicy().hasHeightForWidth())
        self.uiWic2Label.setSizePolicy(sizePolicy)
        self.uiWic2Label.setObjectName(_fromUtf8("uiWic2Label"))
        self.gridlayout2.addWidget(self.uiWic2Label, 2, 0, 1, 1)
        self.uiWic2comboBox = QtGui.QComboBox(self.uiWicsGroupBox)
        self.uiWic2comboBox.setObjectName(_fromUtf8("uiWic2comboBox"))
        self.gridlayout2.addWidget(self.uiWic2comboBox, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.uiWicsGroupBox)
        spacerItem2 = QtGui.QSpacerItem(325, 31, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.uiTabWidget.addTab(self.uiSlotsTabWidget, _fromUtf8(""))
        self.uiAdvancedTabWidget = QtGui.QWidget()
        self.uiAdvancedTabWidget.setObjectName(_fromUtf8("uiAdvancedTabWidget"))
        self.gridlayout3 = QtGui.QGridLayout(self.uiAdvancedTabWidget)
        self.gridlayout3.setObjectName(_fromUtf8("gridlayout3"))
        self.uiConfregLabel = QtGui.QLabel(self.uiAdvancedTabWidget)
        self.uiConfregLabel.setObjectName(_fromUtf8("uiConfregLabel"))
        self.gridlayout3.addWidget(self.uiConfregLabel, 0, 0, 1, 1)
        self.uiConfregLineEdit = QtGui.QLineEdit(self.uiAdvancedTabWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiConfregLineEdit.sizePolicy().hasHeightForWidth())
        self.uiConfregLineEdit.setSizePolicy(sizePolicy)
        self.uiConfregLineEdit.setObjectName(_fromUtf8("uiConfregLineEdit"))
        self.gridlayout3.addWidget(self.uiConfregLineEdit, 0, 1, 1, 1)
        self.uiBaseMacLabel = QtGui.QLabel(self.uiAdvancedTabWidget)
        self.uiBaseMacLabel.setObjectName(_fromUtf8("uiBaseMacLabel"))
        self.gridlayout3.addWidget(self.uiBaseMacLabel, 1, 0, 1, 1)
        self.uiBaseMACLineEdit = QtGui.QLineEdit(self.uiAdvancedTabWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiBaseMACLineEdit.sizePolicy().hasHeightForWidth())
        self.uiBaseMACLineEdit.setSizePolicy(sizePolicy)
        self.uiBaseMACLineEdit.setText(_fromUtf8(""))
        self.uiBaseMACLineEdit.setObjectName(_fromUtf8("uiBaseMACLineEdit"))
        self.gridlayout3.addWidget(self.uiBaseMACLineEdit, 1, 1, 1, 1)
        self.uiExecAreaLabel = QtGui.QLabel(self.uiAdvancedTabWidget)
        self.uiExecAreaLabel.setObjectName(_fromUtf8("uiExecAreaLabel"))
        self.gridlayout3.addWidget(self.uiExecAreaLabel, 2, 0, 1, 1)
        self.uiExecAreaSpinBox = QtGui.QSpinBox(self.uiAdvancedTabWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiExecAreaSpinBox.sizePolicy().hasHeightForWidth())
        self.uiExecAreaSpinBox.setSizePolicy(sizePolicy)
        self.uiExecAreaSpinBox.setMaximum(4096)
        self.uiExecAreaSpinBox.setSingleStep(4)
        self.uiExecAreaSpinBox.setProperty("value", 64)
        self.uiExecAreaSpinBox.setObjectName(_fromUtf8("uiExecAreaSpinBox"))
        self.gridlayout3.addWidget(self.uiExecAreaSpinBox, 2, 1, 1, 1)
        self.uiIomemLabel = QtGui.QLabel(self.uiAdvancedTabWidget)
        self.uiIomemLabel.setObjectName(_fromUtf8("uiIomemLabel"))
        self.gridlayout3.addWidget(self.uiIomemLabel, 3, 0, 1, 1)
        self.uiIomemSpinBox = QtGui.QSpinBox(self.uiAdvancedTabWidget)
        self.uiIomemSpinBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiIomemSpinBox.sizePolicy().hasHeightForWidth())
        self.uiIomemSpinBox.setSizePolicy(sizePolicy)
        self.uiIomemSpinBox.setMaximum(100)
        self.uiIomemSpinBox.setSingleStep(5)
        self.uiIomemSpinBox.setProperty("value", 5)
        self.uiIomemSpinBox.setObjectName(_fromUtf8("uiIomemSpinBox"))
        self.gridlayout3.addWidget(self.uiIomemSpinBox, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(304, 251, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout3.addItem(spacerItem3, 4, 0, 1, 2)
        self.uiTabWidget.addTab(self.uiAdvancedTabWidget, _fromUtf8(""))
        self.vboxlayout.addWidget(self.uiTabWidget)

        self.retranslateUi(routerConfigPageWidget)
        self.uiTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(routerConfigPageWidget)
        routerConfigPageWidget.setTabOrder(self.uiTabWidget, self.uiMidplaneComboBox)
        routerConfigPageWidget.setTabOrder(self.uiMidplaneComboBox, self.uiNPEComboBox)
        routerConfigPageWidget.setTabOrder(self.uiNPEComboBox, self.uiRamSpinBox)
        routerConfigPageWidget.setTabOrder(self.uiRamSpinBox, self.uiNvramSpinBox)
        routerConfigPageWidget.setTabOrder(self.uiNvramSpinBox, self.uiDisk0SpinBox)
        routerConfigPageWidget.setTabOrder(self.uiDisk0SpinBox, self.uiDisk1SpinBox)
        routerConfigPageWidget.setTabOrder(self.uiDisk1SpinBox, self.uiSlot0comboBox)
        routerConfigPageWidget.setTabOrder(self.uiSlot0comboBox, self.uiSlot1comboBox)
        routerConfigPageWidget.setTabOrder(self.uiSlot1comboBox, self.uiSlot2comboBox)
        routerConfigPageWidget.setTabOrder(self.uiSlot2comboBox, self.uiSlot3comboBox)
        routerConfigPageWidget.setTabOrder(self.uiSlot3comboBox, self.uiSlot4comboBox)
        routerConfigPageWidget.setTabOrder(self.uiSlot4comboBox, self.uiSlot5comboBox)
        routerConfigPageWidget.setTabOrder(self.uiSlot5comboBox, self.uiSlot6comboBox)
        routerConfigPageWidget.setTabOrder(self.uiSlot6comboBox, self.uiWic0comboBox)
        routerConfigPageWidget.setTabOrder(self.uiWic0comboBox, self.uiWic1comboBox)
        routerConfigPageWidget.setTabOrder(self.uiWic1comboBox, self.uiWic2comboBox)
        routerConfigPageWidget.setTabOrder(self.uiWic2comboBox, self.uiConfregLineEdit)
        routerConfigPageWidget.setTabOrder(self.uiConfregLineEdit, self.uiBaseMACLineEdit)
        routerConfigPageWidget.setTabOrder(self.uiBaseMACLineEdit, self.uiExecAreaSpinBox)
        routerConfigPageWidget.setTabOrder(self.uiExecAreaSpinBox, self.uiIomemSpinBox)

    def retranslateUi(self, routerConfigPageWidget):
        routerConfigPageWidget.setWindowTitle(_translate("routerConfigPageWidget", "Dynamips IOS Router configuration", None))
        self.uiNameLabel.setText(_translate("routerConfigPageWidget", "Name:", None))
        self.uiConsolePortLabel.setText(_translate("routerConfigPageWidget", "Console port:", None))
        self.uiAuxPortLabel.setText(_translate("routerConfigPageWidget", "Aux console port:", None))
        self.uiPlatformLabel.setText(_translate("routerConfigPageWidget", "Platform:", None))
        self.uiIOSImageLabel.setText(_translate("routerConfigPageWidget", "IOS image:", None))
        self.uiStartupConfigLabel.setText(_translate("routerConfigPageWidget", "Startup-config:", None))
        self.uiMidplaneLabel.setText(_translate("routerConfigPageWidget", "Midplane:", None))
        self.uiNPELabel.setText(_translate("routerConfigPageWidget", "NPE:", None))
        self.uiTabWidget.setTabText(self.uiTabWidget.indexOf(self.uiGeneralTabWidget), _translate("routerConfigPageWidget", "General", None))
        self.uiMemoriesGroupBox.setTitle(_translate("routerConfigPageWidget", "Memories", None))
        self.uiRamLabel.setText(_translate("routerConfigPageWidget", "RAM size:", None))
        self.uiRamSpinBox.setSuffix(_translate("routerConfigPageWidget", " MiB", None))
        self.uiNvramLabel.setText(_translate("routerConfigPageWidget", "NVRAM size:", None))
        self.uiNvramSpinBox.setSuffix(_translate("routerConfigPageWidget", " KiB", None))
        self.uiDisksGroupBox.setTitle(_translate("routerConfigPageWidget", "Disks", None))
        self.uiDisk0Label.setText(_translate("routerConfigPageWidget", "PCMCIA disk0 size:", None))
        self.uiDisk0SpinBox.setSuffix(_translate("routerConfigPageWidget", " MiB", None))
        self.uiDisk1Label.setText(_translate("routerConfigPageWidget", "PCMCIA disk1 size:", None))
        self.uiDisk1SpinBox.setSuffix(_translate("routerConfigPageWidget", " MiB", None))
        self.uiTabWidget.setTabText(self.uiTabWidget.indexOf(self.uiMemoriesTabWidget), _translate("routerConfigPageWidget", "Memories and disks", None))
        self.uiAdaptersGroupBox.setTitle(_translate("routerConfigPageWidget", "Adapters", None))
        self.uiSlot0Label.setText(_translate("routerConfigPageWidget", "slot 0:", None))
        self.uiSlot1Label.setText(_translate("routerConfigPageWidget", "slot 1:", None))
        self.uiSlot2Label.setText(_translate("routerConfigPageWidget", "slot 2:", None))
        self.uiSlot3Label.setText(_translate("routerConfigPageWidget", "slot 3:", None))
        self.uiSlot4Label.setText(_translate("routerConfigPageWidget", "slot 4:", None))
        self.uiSlot5Label.setText(_translate("routerConfigPageWidget", "slot 5:", None))
        self.uiSlot6Label.setText(_translate("routerConfigPageWidget", "slot 6:", None))
        self.uiWicsGroupBox.setTitle(_translate("routerConfigPageWidget", "WICs", None))
        self.uiWic0Label.setText(_translate("routerConfigPageWidget", "wic 0:", None))
        self.uiWic1Label.setText(_translate("routerConfigPageWidget", "wic 1:", None))
        self.uiWic2Label.setText(_translate("routerConfigPageWidget", "wic 2:", None))
        self.uiTabWidget.setTabText(self.uiTabWidget.indexOf(self.uiSlotsTabWidget), _translate("routerConfigPageWidget", "Slots", None))
        self.uiConfregLabel.setText(_translate("routerConfigPageWidget", "Confreg:", None))
        self.uiConfregLineEdit.setText(_translate("routerConfigPageWidget", "0x2102", None))
        self.uiBaseMacLabel.setText(_translate("routerConfigPageWidget", "Base MAC:", None))
        self.uiExecAreaLabel.setText(_translate("routerConfigPageWidget", "Exec area:", None))
        self.uiExecAreaSpinBox.setSuffix(_translate("routerConfigPageWidget", " MiB", None))
        self.uiIomemLabel.setText(_translate("routerConfigPageWidget", "I/O memory :", None))
        self.uiIomemSpinBox.setSuffix(_translate("routerConfigPageWidget", " %", None))
        self.uiTabWidget.setTabText(self.uiTabWidget.indexOf(self.uiAdvancedTabWidget), _translate("routerConfigPageWidget", "Advanced", None))

