# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/grossmj/workspace/git/gns3-gui/gns3/modules/iou/ui/iou_device_preferences_page.ui'
#
# Created: Mon May 19 15:05:35 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_IOUDevicePreferencesPageWidget(object):
    def setupUi(self, IOUDevicePreferencesPageWidget):
        IOUDevicePreferencesPageWidget.setObjectName(_fromUtf8("IOUDevicePreferencesPageWidget"))
        IOUDevicePreferencesPageWidget.resize(411, 544)
        self.vboxlayout = QtGui.QVBoxLayout(IOUDevicePreferencesPageWidget)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.uiTabWidget = QtGui.QTabWidget(IOUDevicePreferencesPageWidget)
        self.uiTabWidget.setEnabled(True)
        self.uiTabWidget.setObjectName(_fromUtf8("uiTabWidget"))
        self.uiIOUDeviceTabWidget = QtGui.QWidget()
        self.uiIOUDeviceTabWidget.setObjectName(_fromUtf8("uiIOUDeviceTabWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.uiIOUDeviceTabWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.uiIOUImagesTreeWidget = QtGui.QTreeWidget(self.uiIOUDeviceTabWidget)
        self.uiIOUImagesTreeWidget.setObjectName(_fromUtf8("uiIOUImagesTreeWidget"))
        self.verticalLayout_2.addWidget(self.uiIOUImagesTreeWidget)
        self.uiGeneralGroupBox = QtGui.QGroupBox(self.uiIOUDeviceTabWidget)
        self.uiGeneralGroupBox.setObjectName(_fromUtf8("uiGeneralGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.uiGeneralGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.uiIOUPathLabel = QtGui.QLabel(self.uiGeneralGroupBox)
        self.uiIOUPathLabel.setObjectName(_fromUtf8("uiIOUPathLabel"))
        self.gridLayout_2.addWidget(self.uiIOUPathLabel, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.uiIOUPathLineEdit = QtGui.QLineEdit(self.uiGeneralGroupBox)
        self.uiIOUPathLineEdit.setObjectName(_fromUtf8("uiIOUPathLineEdit"))
        self.horizontalLayout_3.addWidget(self.uiIOUPathLineEdit)
        self.uiIOUPathToolButton = QtGui.QToolButton(self.uiGeneralGroupBox)
        self.uiIOUPathToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.uiIOUPathToolButton.setObjectName(_fromUtf8("uiIOUPathToolButton"))
        self.horizontalLayout_3.addWidget(self.uiIOUPathToolButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.uiStartupConfigLabel = QtGui.QLabel(self.uiGeneralGroupBox)
        self.uiStartupConfigLabel.setObjectName(_fromUtf8("uiStartupConfigLabel"))
        self.gridLayout_2.addWidget(self.uiStartupConfigLabel, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.uiStartupConfigLineEdit = QtGui.QLineEdit(self.uiGeneralGroupBox)
        self.uiStartupConfigLineEdit.setObjectName(_fromUtf8("uiStartupConfigLineEdit"))
        self.horizontalLayout_4.addWidget(self.uiStartupConfigLineEdit)
        self.uiStartupConfigToolButton = QtGui.QToolButton(self.uiGeneralGroupBox)
        self.uiStartupConfigToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.uiStartupConfigToolButton.setObjectName(_fromUtf8("uiStartupConfigToolButton"))
        self.horizontalLayout_4.addWidget(self.uiStartupConfigToolButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.uiGeneralGroupBox)
        self.uiAdvancedSettingsGroupBox = QtGui.QGroupBox(self.uiIOUDeviceTabWidget)
        self.uiAdvancedSettingsGroupBox.setObjectName(_fromUtf8("uiAdvancedSettingsGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.uiAdvancedSettingsGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.uiDefaultValuesCheckBox = QtGui.QCheckBox(self.uiAdvancedSettingsGroupBox)
        self.uiDefaultValuesCheckBox.setChecked(True)
        self.uiDefaultValuesCheckBox.setObjectName(_fromUtf8("uiDefaultValuesCheckBox"))
        self.gridLayout_3.addWidget(self.uiDefaultValuesCheckBox, 1, 0, 1, 2)
        self.uiRAMLabel = QtGui.QLabel(self.uiAdvancedSettingsGroupBox)
        self.uiRAMLabel.setObjectName(_fromUtf8("uiRAMLabel"))
        self.gridLayout_3.addWidget(self.uiRAMLabel, 3, 0, 1, 1)
        self.uiRAMSpinBox = QtGui.QSpinBox(self.uiAdvancedSettingsGroupBox)
        self.uiRAMSpinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiRAMSpinBox.sizePolicy().hasHeightForWidth())
        self.uiRAMSpinBox.setSizePolicy(sizePolicy)
        self.uiRAMSpinBox.setMinimum(16)
        self.uiRAMSpinBox.setMaximum(65535)
        self.uiRAMSpinBox.setProperty("value", 256)
        self.uiRAMSpinBox.setObjectName(_fromUtf8("uiRAMSpinBox"))
        self.gridLayout_3.addWidget(self.uiRAMSpinBox, 3, 1, 1, 1)
        self.uiNVRAMLabel = QtGui.QLabel(self.uiAdvancedSettingsGroupBox)
        self.uiNVRAMLabel.setObjectName(_fromUtf8("uiNVRAMLabel"))
        self.gridLayout_3.addWidget(self.uiNVRAMLabel, 4, 0, 1, 1)
        self.uiNVRAMSpinBox = QtGui.QSpinBox(self.uiAdvancedSettingsGroupBox)
        self.uiNVRAMSpinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiNVRAMSpinBox.sizePolicy().hasHeightForWidth())
        self.uiNVRAMSpinBox.setSizePolicy(sizePolicy)
        self.uiNVRAMSpinBox.setMinimum(16)
        self.uiNVRAMSpinBox.setMaximum(65535)
        self.uiNVRAMSpinBox.setProperty("value", 128)
        self.uiNVRAMSpinBox.setObjectName(_fromUtf8("uiNVRAMSpinBox"))
        self.gridLayout_3.addWidget(self.uiNVRAMSpinBox, 4, 1, 1, 1)
        self.uiL1KeepalivesCheckBox = QtGui.QCheckBox(self.uiAdvancedSettingsGroupBox)
        self.uiL1KeepalivesCheckBox.setChecked(True)
        self.uiL1KeepalivesCheckBox.setObjectName(_fromUtf8("uiL1KeepalivesCheckBox"))
        self.gridLayout_3.addWidget(self.uiL1KeepalivesCheckBox, 0, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.uiAdvancedSettingsGroupBox)
        spacerItem = QtGui.QSpacerItem(76, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.uiIOUImageTestSettingsPushButton = QtGui.QPushButton(self.uiIOUDeviceTabWidget)
        self.uiIOUImageTestSettingsPushButton.setObjectName(_fromUtf8("uiIOUImageTestSettingsPushButton"))
        self.horizontalLayout_5.addWidget(self.uiIOUImageTestSettingsPushButton)
        self.uiSaveIOUImagePushButton = QtGui.QPushButton(self.uiIOUDeviceTabWidget)
        self.uiSaveIOUImagePushButton.setObjectName(_fromUtf8("uiSaveIOUImagePushButton"))
        self.horizontalLayout_5.addWidget(self.uiSaveIOUImagePushButton)
        self.uiDeleteIOUImagePushButton = QtGui.QPushButton(self.uiIOUDeviceTabWidget)
        self.uiDeleteIOUImagePushButton.setEnabled(False)
        self.uiDeleteIOUImagePushButton.setObjectName(_fromUtf8("uiDeleteIOUImagePushButton"))
        self.horizontalLayout_5.addWidget(self.uiDeleteIOUImagePushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.uiTabWidget.addTab(self.uiIOUDeviceTabWidget, _fromUtf8(""))
        self.uiIOSRoutersTabWidget = QtGui.QWidget()
        self.uiIOSRoutersTabWidget.setEnabled(False)
        self.uiIOSRoutersTabWidget.setObjectName(_fromUtf8("uiIOSRoutersTabWidget"))
        self.gridLayout = QtGui.QGridLayout(self.uiIOSRoutersTabWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.treeWidget_2 = QtGui.QTreeWidget(self.uiIOSRoutersTabWidget)
        self.treeWidget_2.setObjectName(_fromUtf8("treeWidget_2"))
        self.gridLayout.addWidget(self.treeWidget_2, 0, 0, 2, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_3 = QtGui.QPushButton(self.uiIOSRoutersTabWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.uiIOSRoutersTabWidget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.uiIOSRoutersTabWidget)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout.addWidget(self.pushButton_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 354, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.uiTabWidget.addTab(self.uiIOSRoutersTabWidget, _fromUtf8(""))
        self.vboxlayout.addWidget(self.uiTabWidget)

        self.retranslateUi(IOUDevicePreferencesPageWidget)
        self.uiTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(IOUDevicePreferencesPageWidget)

    def retranslateUi(self, IOUDevicePreferencesPageWidget):
        IOUDevicePreferencesPageWidget.setWindowTitle(_translate("IOUDevicePreferencesPageWidget", "IOU devices", None))
        self.uiIOUImagesTreeWidget.headerItem().setText(0, _translate("IOUDevicePreferencesPageWidget", "File", None))
        self.uiIOUImagesTreeWidget.headerItem().setText(1, _translate("IOUDevicePreferencesPageWidget", "Server", None))
        self.uiGeneralGroupBox.setTitle(_translate("IOUDevicePreferencesPageWidget", "General", None))
        self.uiIOUPathLabel.setText(_translate("IOUDevicePreferencesPageWidget", "IOU path:", None))
        self.uiIOUPathToolButton.setText(_translate("IOUDevicePreferencesPageWidget", "...", None))
        self.uiStartupConfigLabel.setText(_translate("IOUDevicePreferencesPageWidget", "Startup-config:", None))
        self.uiStartupConfigToolButton.setText(_translate("IOUDevicePreferencesPageWidget", "...", None))
        self.uiAdvancedSettingsGroupBox.setTitle(_translate("IOUDevicePreferencesPageWidget", "Advanced settings", None))
        self.uiDefaultValuesCheckBox.setText(_translate("IOUDevicePreferencesPageWidget", "Use default IOU values for memories", None))
        self.uiRAMLabel.setText(_translate("IOUDevicePreferencesPageWidget", "RAM:", None))
        self.uiRAMSpinBox.setSuffix(_translate("IOUDevicePreferencesPageWidget", " MB", None))
        self.uiNVRAMLabel.setText(_translate("IOUDevicePreferencesPageWidget", "NVRAM:", None))
        self.uiNVRAMSpinBox.setSuffix(_translate("IOUDevicePreferencesPageWidget", " KB", None))
        self.uiL1KeepalivesCheckBox.setText(_translate("IOUDevicePreferencesPageWidget", "Enable layer 1 keepalive messages if supported", None))
        self.uiIOUImageTestSettingsPushButton.setText(_translate("IOUDevicePreferencesPageWidget", "Test settings", None))
        self.uiSaveIOUImagePushButton.setText(_translate("IOUDevicePreferencesPageWidget", "Save", None))
        self.uiDeleteIOUImagePushButton.setText(_translate("IOUDevicePreferencesPageWidget", "Delete", None))
        self.uiTabWidget.setTabText(self.uiTabWidget.indexOf(self.uiIOUDeviceTabWidget), _translate("IOUDevicePreferencesPageWidget", "IOU images", None))
        self.treeWidget_2.headerItem().setText(0, _translate("IOUDevicePreferencesPageWidget", "IOU device", None))
        self.treeWidget_2.headerItem().setText(1, _translate("IOUDevicePreferencesPageWidget", "IOU file", None))
        self.pushButton_3.setText(_translate("IOUDevicePreferencesPageWidget", "New", None))
        self.pushButton_4.setText(_translate("IOUDevicePreferencesPageWidget", "Edit", None))
        self.pushButton_5.setText(_translate("IOUDevicePreferencesPageWidget", "Delete", None))
        self.uiTabWidget.setTabText(self.uiTabWidget.indexOf(self.uiIOSRoutersTabWidget), _translate("IOUDevicePreferencesPageWidget", "IOU devices", None))

