# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cloud_preferences_page.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

import gns3.qt
from gns3.qt import QtCore, QtGui, QtWidgets

class Ui_CloudPreferencesPageWidget(object):
    def setupUi(self, CloudPreferencesPageWidget):
        CloudPreferencesPageWidget.setObjectName("CloudPreferencesPageWidget")
        CloudPreferencesPageWidget.resize(482, 485)
        self.gridLayout = QtWidgets.QGridLayout(CloudPreferencesPageWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.uiImageTemplateLabel = QtWidgets.QLabel(CloudPreferencesPageWidget)
        self.uiImageTemplateLabel.setObjectName("uiImageTemplateLabel")
        self.gridLayout.addWidget(self.uiImageTemplateLabel, 16, 0, 1, 3)
        self.uiImageTemplateComboBox = QtWidgets.QComboBox(CloudPreferencesPageWidget)
        self.uiImageTemplateComboBox.setObjectName("uiImageTemplateComboBox")
        self.gridLayout.addWidget(self.uiImageTemplateComboBox, 17, 0, 1, 1)
        self.uiNewInstancesLabel = QtWidgets.QLabel(CloudPreferencesPageWidget)
        self.uiNewInstancesLabel.setObjectName("uiNewInstancesLabel")
        self.gridLayout.addWidget(self.uiNewInstancesLabel, 9, 0, 1, 3)
        self.uiCreateAccountLabel = QtWidgets.QLabel(CloudPreferencesPageWidget)
        self.uiCreateAccountLabel.setTextFormat(QtCore.Qt.RichText)
        self.uiCreateAccountLabel.setObjectName("uiCreateAccountLabel")
        self.gridLayout.addWidget(self.uiCreateAccountLabel, 2, 2, 1, 1)
        self.uiUserNameLineEdit = QtWidgets.QLineEdit(CloudPreferencesPageWidget)
        self.uiUserNameLineEdit.setObjectName("uiUserNameLineEdit")
        self.gridLayout.addWidget(self.uiUserNameLineEdit, 1, 0, 1, 1)
        self.uiAPIKeyLineEdit = QtWidgets.QLineEdit(CloudPreferencesPageWidget)
        self.uiAPIKeyLineEdit.setObjectName("uiAPIKeyLineEdit")
        self.gridLayout.addWidget(self.uiAPIKeyLineEdit, 1, 2, 1, 1)
        self.uiStartNewProjectLayout = QtWidgets.QHBoxLayout()
        self.uiStartNewProjectLayout.setObjectName("uiStartNewProjectLayout")
        self.uiNumOfInstancesSpinBox = QtWidgets.QSpinBox(CloudPreferencesPageWidget)
        self.uiNumOfInstancesSpinBox.setObjectName("uiNumOfInstancesSpinBox")
        self.uiStartNewProjectLayout.addWidget(self.uiNumOfInstancesSpinBox)
        self.uiNumOfInstancesLabel = QtWidgets.QLabel(CloudPreferencesPageWidget)
        self.uiNumOfInstancesLabel.setObjectName("uiNumOfInstancesLabel")
        self.uiStartNewProjectLayout.addWidget(self.uiNumOfInstancesLabel)
        self.uiInstanceFlavorComboBox = QtWidgets.QComboBox(CloudPreferencesPageWidget)
        self.uiInstanceFlavorComboBox.setObjectName("uiInstanceFlavorComboBox")
        self.uiStartNewProjectLayout.addWidget(self.uiInstanceFlavorComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uiStartNewProjectLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.uiStartNewProjectLayout, 7, 0, 1, 3)
        self.uiTimeoutLabel = QtWidgets.QLabel(CloudPreferencesPageWidget)
        self.uiTimeoutLabel.setWordWrap(True)
        self.uiTimeoutLabel.setObjectName("uiTimeoutLabel")
        self.gridLayout.addWidget(self.uiTimeoutLabel, 12, 0, 1, 2)
        self.uiNewInstancesLayout = QtWidgets.QHBoxLayout()
        self.uiNewInstancesLayout.setObjectName("uiNewInstancesLayout")
        self.uiNewInstanceFlavorComboBox = QtWidgets.QComboBox(CloudPreferencesPageWidget)
        self.uiNewInstanceFlavorComboBox.setObjectName("uiNewInstanceFlavorComboBox")
        self.uiNewInstancesLayout.addWidget(self.uiNewInstanceFlavorComboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uiNewInstancesLayout.addItem(spacerItem1)
        self.uiTermsCheckBox = QtWidgets.QCheckBox(CloudPreferencesPageWidget)
        self.uiTermsCheckBox.setText("")
        self.uiTermsCheckBox.setObjectName("uiTermsCheckBox")
        self.uiNewInstancesLayout.addWidget(self.uiTermsCheckBox)
        self.uiTermsLabel = QtWidgets.QLabel(CloudPreferencesPageWidget)
        self.uiTermsLabel.setTextFormat(QtCore.Qt.RichText)
        self.uiTermsLabel.setObjectName("uiTermsLabel")
        self.uiNewInstancesLayout.addWidget(self.uiTermsLabel)
        self.gridLayout.addLayout(self.uiNewInstancesLayout, 10, 0, 2, 3)
        self.uiCloudProviderComboBox = QtWidgets.QComboBox(CloudPreferencesPageWidget)
        self.uiCloudProviderComboBox.setObjectName("uiCloudProviderComboBox")
        self.gridLayout.addWidget(self.uiCloudProviderComboBox, 3, 0, 1, 1)
        self.uiUserNameLabel = QtWidgets.QLabel(CloudPreferencesPageWidget)
        self.uiUserNameLabel.setObjectName("uiUserNameLabel")
        self.gridLayout.addWidget(self.uiUserNameLabel, 0, 0, 1, 1)
        self.uiAPIKeyLabel = QtWidgets.QLabel(CloudPreferencesPageWidget)
        self.uiAPIKeyLabel.setObjectName("uiAPIKeyLabel")
        self.gridLayout.addWidget(self.uiAPIKeyLabel, 0, 2, 1, 1)
        self.uiRememberAPIKeyRadioButton = QtWidgets.QRadioButton(CloudPreferencesPageWidget)
        self.uiRememberAPIKeyRadioButton.setObjectName("uiRememberAPIKeyRadioButton")
        self.gridLayout.addWidget(self.uiRememberAPIKeyRadioButton, 3, 2, 1, 1)
        self.uiStartNewProjectsLabel = QtWidgets.QLabel(CloudPreferencesPageWidget)
        self.uiStartNewProjectsLabel.setObjectName("uiStartNewProjectsLabel")
        self.gridLayout.addWidget(self.uiStartNewProjectsLabel, 6, 0, 1, 3)
        self.uiRegionComboBox = QtWidgets.QComboBox(CloudPreferencesPageWidget)
        self.uiRegionComboBox.setObjectName("uiRegionComboBox")
        self.gridLayout.addWidget(self.uiRegionComboBox, 5, 0, 1, 1)
        self.uiCloudProviderLabel = QtWidgets.QLabel(CloudPreferencesPageWidget)
        self.uiCloudProviderLabel.setObjectName("uiCloudProviderLabel")
        self.gridLayout.addWidget(self.uiCloudProviderLabel, 2, 0, 1, 1)
        self.uiRegionLabel = QtWidgets.QLabel(CloudPreferencesPageWidget)
        self.uiRegionLabel.setObjectName("uiRegionLabel")
        self.gridLayout.addWidget(self.uiRegionLabel, 4, 0, 1, 1)
        self.uiForgetAPIKeyRadioButton = QtWidgets.QRadioButton(CloudPreferencesPageWidget)
        self.uiForgetAPIKeyRadioButton.setObjectName("uiForgetAPIKeyRadioButton")
        self.gridLayout.addWidget(self.uiForgetAPIKeyRadioButton, 4, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.uiTimeoutSpinBox = QtWidgets.QSpinBox(CloudPreferencesPageWidget)
        self.uiTimeoutSpinBox.setMaximum(999)
        self.uiTimeoutSpinBox.setProperty("value", 30)
        self.uiTimeoutSpinBox.setObjectName("uiTimeoutSpinBox")
        self.horizontalLayout_3.addWidget(self.uiTimeoutSpinBox)
        self.uiTimeoutLabel2 = QtWidgets.QLabel(CloudPreferencesPageWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiTimeoutLabel2.sizePolicy().hasHeightForWidth())
        self.uiTimeoutLabel2.setSizePolicy(sizePolicy)
        self.uiTimeoutLabel2.setObjectName("uiTimeoutLabel2")
        self.horizontalLayout_3.addWidget(self.uiTimeoutLabel2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 14, 0, 2, 3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 18, 0, 1, 1)

        self.retranslateUi(CloudPreferencesPageWidget)
        QtCore.QMetaObject.connectSlotsByName(CloudPreferencesPageWidget)

    def retranslateUi(self, CloudPreferencesPageWidget):
        _translate = gns3.qt.translate
        CloudPreferencesPageWidget.setWindowTitle(_translate("CloudPreferencesPageWidget", "Cloud"))
        self.uiImageTemplateLabel.setText(_translate("CloudPreferencesPageWidget", "New instances use the following template:"))
        self.uiNewInstancesLabel.setText(_translate("CloudPreferencesPageWidget", "New instances are:"))
        self.uiCreateAccountLabel.setText(_translate("CloudPreferencesPageWidget", "No API Key? <a href=\"#\">Create Cloud Account.</a>"))
        self.uiNumOfInstancesLabel.setText(_translate("CloudPreferencesPageWidget", "instance(s) with"))
        self.uiTimeoutLabel.setText(_translate("CloudPreferencesPageWidget", "Instances are deleted after"))
        self.uiTermsLabel.setText(_translate("CloudPreferencesPageWidget", "Accept Terms and Conditions"))
        self.uiUserNameLabel.setText(_translate("CloudPreferencesPageWidget", "User Name:"))
        self.uiAPIKeyLabel.setText(_translate("CloudPreferencesPageWidget", "API Key"))
        self.uiRememberAPIKeyRadioButton.setText(_translate("CloudPreferencesPageWidget", "Remeber these settings\n"
"(Suggested for private computers)"))
        self.uiStartNewProjectsLabel.setText(_translate("CloudPreferencesPageWidget", "Start new projects with:"))
        self.uiCloudProviderLabel.setText(_translate("CloudPreferencesPageWidget", "Cloud provider"))
        self.uiRegionLabel.setText(_translate("CloudPreferencesPageWidget", "Region (optional)"))
        self.uiForgetAPIKeyRadioButton.setText(_translate("CloudPreferencesPageWidget", "Forget these settings on exit\n"
"(Suggested for public computers)"))
        self.uiTimeoutLabel2.setText(_translate("CloudPreferencesPageWidget", "minutes of lost communication"))

