# Form implementation generated from reading ui file '/home/grossmj/PycharmProjects/gns3-gui/gns3/ui/custom_adapters_configuration_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CustomAdaptersConfigurationDialog(object):
    def setupUi(self, CustomAdaptersConfigurationDialog):
        CustomAdaptersConfigurationDialog.setObjectName("CustomAdaptersConfigurationDialog")
        CustomAdaptersConfigurationDialog.resize(718, 450)
        CustomAdaptersConfigurationDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(CustomAdaptersConfigurationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.uiAdaptersTreeWidget = QtWidgets.QTreeWidget(parent=CustomAdaptersConfigurationDialog)
        self.uiAdaptersTreeWidget.setObjectName("uiAdaptersTreeWidget")
        self.verticalLayout.addWidget(self.uiAdaptersTreeWidget)
        self.uiButtonBox = QtWidgets.QDialogButtonBox(parent=CustomAdaptersConfigurationDialog)
        self.uiButtonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.uiButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok|QtWidgets.QDialogButtonBox.StandardButton.Reset)
        self.uiButtonBox.setObjectName("uiButtonBox")
        self.verticalLayout.addWidget(self.uiButtonBox)

        self.retranslateUi(CustomAdaptersConfigurationDialog)
        self.uiButtonBox.accepted.connect(CustomAdaptersConfigurationDialog.accept) # type: ignore
        self.uiButtonBox.rejected.connect(CustomAdaptersConfigurationDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CustomAdaptersConfigurationDialog)

    def retranslateUi(self, CustomAdaptersConfigurationDialog):
        _translate = QtCore.QCoreApplication.translate
        CustomAdaptersConfigurationDialog.setWindowTitle(_translate("CustomAdaptersConfigurationDialog", "Custom adapters configuration"))
        self.uiAdaptersTreeWidget.headerItem().setText(0, _translate("CustomAdaptersConfigurationDialog", "Adapter number"))
        self.uiAdaptersTreeWidget.headerItem().setText(1, _translate("CustomAdaptersConfigurationDialog", "Port name"))
