# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/grossmj/PycharmProjects/gns3-gui/gns3/ui/edit_compute_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditComputeDialog(object):
    def setupUi(self, EditComputeDialog):
        EditComputeDialog.setObjectName("EditComputeDialog")
        EditComputeDialog.setWindowModality(QtCore.Qt.WindowModal)
        EditComputeDialog.resize(439, 280)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditComputeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(EditComputeDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.uiServerNameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.uiServerNameLineEdit.setObjectName("uiServerNameLineEdit")
        self.gridLayout.addWidget(self.uiServerNameLineEdit, 0, 1, 1, 1)
        self.uiServerProtocolLabel = QtWidgets.QLabel(self.groupBox)
        self.uiServerProtocolLabel.setObjectName("uiServerProtocolLabel")
        self.gridLayout.addWidget(self.uiServerProtocolLabel, 1, 0, 1, 1)
        self.uiServerProtocolComboBox = QtWidgets.QComboBox(self.groupBox)
        self.uiServerProtocolComboBox.setObjectName("uiServerProtocolComboBox")
        self.uiServerProtocolComboBox.addItem("")
        self.uiServerProtocolComboBox.addItem("")
        self.gridLayout.addWidget(self.uiServerProtocolComboBox, 1, 1, 1, 1)
        self.uiServerHostLabel = QtWidgets.QLabel(self.groupBox)
        self.uiServerHostLabel.setObjectName("uiServerHostLabel")
        self.gridLayout.addWidget(self.uiServerHostLabel, 2, 0, 1, 1)
        self.uiServerHostLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.uiServerHostLineEdit.setObjectName("uiServerHostLineEdit")
        self.gridLayout.addWidget(self.uiServerHostLineEdit, 2, 1, 1, 1)
        self.uiServerPortLabel = QtWidgets.QLabel(self.groupBox)
        self.uiServerPortLabel.setObjectName("uiServerPortLabel")
        self.gridLayout.addWidget(self.uiServerPortLabel, 3, 0, 1, 1)
        self.uiServerPortSpinBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiServerPortSpinBox.sizePolicy().hasHeightForWidth())
        self.uiServerPortSpinBox.setSizePolicy(sizePolicy)
        self.uiServerPortSpinBox.setSuffix(" TCP")
        self.uiServerPortSpinBox.setMaximum(65535)
        self.uiServerPortSpinBox.setProperty("value", 3080)
        self.uiServerPortSpinBox.setObjectName("uiServerPortSpinBox")
        self.gridLayout.addWidget(self.uiServerPortSpinBox, 3, 1, 1, 1)
        self.uiServerUserLabel = QtWidgets.QLabel(self.groupBox)
        self.uiServerUserLabel.setObjectName("uiServerUserLabel")
        self.gridLayout.addWidget(self.uiServerUserLabel, 4, 0, 1, 1)
        self.uiServerUserLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.uiServerUserLineEdit.setEnabled(True)
        self.uiServerUserLineEdit.setToolTip("")
        self.uiServerUserLineEdit.setObjectName("uiServerUserLineEdit")
        self.gridLayout.addWidget(self.uiServerUserLineEdit, 4, 1, 1, 1)
        self.uiServerPasswordLabel = QtWidgets.QLabel(self.groupBox)
        self.uiServerPasswordLabel.setObjectName("uiServerPasswordLabel")
        self.gridLayout.addWidget(self.uiServerPasswordLabel, 5, 0, 1, 1)
        self.uiServerPasswordLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.uiServerPasswordLineEdit.setEnabled(True)
        self.uiServerPasswordLineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.uiServerPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.uiServerPasswordLineEdit.setObjectName("uiServerPasswordLineEdit")
        self.gridLayout.addWidget(self.uiServerPasswordLineEdit, 5, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditComputeDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(EditComputeDialog)
        self.buttonBox.accepted.connect(EditComputeDialog.accept)
        self.buttonBox.rejected.connect(EditComputeDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EditComputeDialog)
        EditComputeDialog.setTabOrder(self.uiServerNameLineEdit, self.uiServerHostLineEdit)
        EditComputeDialog.setTabOrder(self.uiServerHostLineEdit, self.uiServerPortSpinBox)

    def retranslateUi(self, EditComputeDialog):
        _translate = QtCore.QCoreApplication.translate
        EditComputeDialog.setWindowTitle(_translate("EditComputeDialog", "Edit compute settings"))
        self.groupBox.setTitle(_translate("EditComputeDialog", "Compute settings"))
        self.label.setText(_translate("EditComputeDialog", "Name:"))
        self.uiServerProtocolLabel.setText(_translate("EditComputeDialog", "Protocol:"))
        self.uiServerProtocolComboBox.setItemText(0, _translate("EditComputeDialog", "HTTP"))
        self.uiServerProtocolComboBox.setItemText(1, _translate("EditComputeDialog", "HTTPS"))
        self.uiServerHostLabel.setText(_translate("EditComputeDialog", "Host:"))
        self.uiServerHostLineEdit.setText(_translate("EditComputeDialog", "192.168.56.101"))
        self.uiServerPortLabel.setText(_translate("EditComputeDialog", "Port:"))
        self.uiServerUserLabel.setText(_translate("EditComputeDialog", "Username:"))
        self.uiServerPasswordLabel.setText(_translate("EditComputeDialog", "Password:"))
