# Form implementation generated from reading ui file '/home/grossmj/PycharmProjects/gns3-gui/gns3/ui/image_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImageDialog(object):
    def setupUi(self, ImageDialog):
        ImageDialog.setObjectName("ImageDialog")
        ImageDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        ImageDialog.resize(849, 328)
        ImageDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(ImageDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.uiImagesTreeWidget = QtWidgets.QTreeWidget(parent=ImageDialog)
        self.uiImagesTreeWidget.setAlternatingRowColors(True)
        self.uiImagesTreeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.uiImagesTreeWidget.setObjectName("uiImagesTreeWidget")
        self.uiImagesTreeWidget.header().setSortIndicatorShown(True)
        self.gridLayout.addWidget(self.uiImagesTreeWidget, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiUploadImagePushButton = QtWidgets.QPushButton(parent=ImageDialog)
        self.uiUploadImagePushButton.setObjectName("uiUploadImagePushButton")
        self.horizontalLayout.addWidget(self.uiUploadImagePushButton)
        self.uiDeleteImagePushButton = QtWidgets.QPushButton(parent=ImageDialog)
        self.uiDeleteImagePushButton.setObjectName("uiDeleteImagePushButton")
        self.horizontalLayout.addWidget(self.uiDeleteImagePushButton)
        self.uiInstallApplianceCheckBox = QtWidgets.QCheckBox(parent=ImageDialog)
        self.uiInstallApplianceCheckBox.setChecked(True)
        self.uiInstallApplianceCheckBox.setObjectName("uiInstallApplianceCheckBox")
        self.horizontalLayout.addWidget(self.uiInstallApplianceCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uiInstallAllPushButton = QtWidgets.QPushButton(parent=ImageDialog)
        self.uiInstallAllPushButton.setObjectName("uiInstallAllPushButton")
        self.horizontalLayout.addWidget(self.uiInstallAllPushButton)
        self.uiPruneImagesPushButton = QtWidgets.QPushButton(parent=ImageDialog)
        self.uiPruneImagesPushButton.setObjectName("uiPruneImagesPushButton")
        self.horizontalLayout.addWidget(self.uiPruneImagesPushButton)
        self.uiRefreshImagesPushButton = QtWidgets.QPushButton(parent=ImageDialog)
        self.uiRefreshImagesPushButton.setObjectName("uiRefreshImagesPushButton")
        self.horizontalLayout.addWidget(self.uiRefreshImagesPushButton)
        self.uiButtonBox = QtWidgets.QDialogButtonBox(parent=ImageDialog)
        self.uiButtonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.uiButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.uiButtonBox.setObjectName("uiButtonBox")
        self.horizontalLayout.addWidget(self.uiButtonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(ImageDialog)
        self.uiButtonBox.accepted.connect(ImageDialog.accept) # type: ignore
        self.uiButtonBox.rejected.connect(ImageDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ImageDialog)

    def retranslateUi(self, ImageDialog):
        _translate = QtCore.QCoreApplication.translate
        ImageDialog.setWindowTitle(_translate("ImageDialog", "Images"))
        self.uiImagesTreeWidget.setSortingEnabled(True)
        self.uiImagesTreeWidget.headerItem().setText(0, _translate("ImageDialog", "Filename"))
        self.uiImagesTreeWidget.headerItem().setText(1, _translate("ImageDialog", "Type"))
        self.uiImagesTreeWidget.headerItem().setText(2, _translate("ImageDialog", "Size"))
        self.uiUploadImagePushButton.setText(_translate("ImageDialog", "&Upload"))
        self.uiDeleteImagePushButton.setText(_translate("ImageDialog", "&Delete"))
        self.uiInstallApplianceCheckBox.setText(_translate("ImageDialog", "&Install appliance(s) after upload"))
        self.uiInstallAllPushButton.setText(_translate("ImageDialog", "&Install all"))
        self.uiPruneImagesPushButton.setText(_translate("ImageDialog", "&Prune"))
        self.uiRefreshImagesPushButton.setText(_translate("ImageDialog", "&Refresh"))
