# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/grossmj/workspace/git/gns3-gui/gns3/ui/main_window.ui'
#
# Created: Sun Jan 26 13:50:52 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(980, 719)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/logo_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("#toolBar_Devices QToolButton {\n"
"width: 50px;\n"
"height: 55px;\n"
"border:solid 1px black opacity 0.4;\n"
"background-none;\n"
"}\n"
"\n"
"#toolBar_General QToolButton {\n"
"width: 36px;\n"
"height: 36px;\n"
"border:solid 1px black opacity 0.4;\n"
"background-none;\n"
"}\n"
"\n"
""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridlayout = QtGui.QGridLayout(self.centralwidget)
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.uiGraphicsView = GraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiGraphicsView.sizePolicy().hasHeightForWidth())
        self.uiGraphicsView.setSizePolicy(sizePolicy)
        self.uiGraphicsView.setObjectName(_fromUtf8("uiGraphicsView"))
        self.gridlayout.addWidget(self.uiGraphicsView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_About = QtGui.QMenu(self.menubar)
        self.menu_About.setObjectName(_fromUtf8("menu_About"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menuWindow_Style = QtGui.QMenu(self.menu_View)
        self.menuWindow_Style.setObjectName(_fromUtf8("menuWindow_Style"))
        self.menuControl = QtGui.QMenu(self.menubar)
        self.menuControl.setObjectName(_fromUtf8("menuControl"))
        self.menuAnnotate = QtGui.QMenu(self.menubar)
        self.menuAnnotate.setObjectName(_fromUtf8("menuAnnotate"))
        self.menuDevice = QtGui.QMenu(self.menubar)
        self.menuDevice.setObjectName(_fromUtf8("menuDevice"))
        self.menu_Tools = QtGui.QMenu(self.menubar)
        self.menu_Tools.setObjectName(_fromUtf8("menu_Tools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar_General = QtGui.QToolBar(MainWindow)
        self.toolBar_General.setToolTip(_fromUtf8(""))
        self.toolBar_General.setStatusTip(_fromUtf8(""))
        self.toolBar_General.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar_General.setIconSize(QtCore.QSize(32, 32))
        self.toolBar_General.setObjectName(_fromUtf8("toolBar_General"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_General)
        self.uiNodesDockWidget = QtGui.QDockWidget(MainWindow)
        self.uiNodesDockWidget.setEnabled(True)
        self.uiNodesDockWidget.setVisible(True)
        self.uiNodesDockWidget.setFloating(False)
        self.uiNodesDockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.uiNodesDockWidget.setObjectName(_fromUtf8("uiNodesDockWidget"))
        self.uiNodesDockWidgetContents = QtGui.QWidget()
        self.uiNodesDockWidgetContents.setObjectName(_fromUtf8("uiNodesDockWidgetContents"))
        self.vboxlayout = QtGui.QVBoxLayout(self.uiNodesDockWidgetContents)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.uiNodesView = NodesView(self.uiNodesDockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiNodesView.sizePolicy().hasHeightForWidth())
        self.uiNodesView.setSizePolicy(sizePolicy)
        self.uiNodesView.setDragEnabled(False)
        self.uiNodesView.setIconSize(QtCore.QSize(24, 24))
        self.uiNodesView.setRootIsDecorated(False)
        self.uiNodesView.setObjectName(_fromUtf8("uiNodesView"))
        self.uiNodesView.header().setVisible(False)
        self.vboxlayout.addWidget(self.uiNodesView)
        self.uiNodesDockWidget.setWidget(self.uiNodesDockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.uiNodesDockWidget)
        self.toolBar_Devices = QtGui.QToolBar(MainWindow)
        self.toolBar_Devices.setIconSize(QtCore.QSize(64, 64))
        self.toolBar_Devices.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar_Devices.setObjectName(_fromUtf8("toolBar_Devices"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar_Devices)
        self.toolBar_Emulation = QtGui.QToolBar(MainWindow)
        self.toolBar_Emulation.setIconSize(QtCore.QSize(32, 32))
        self.toolBar_Emulation.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar_Emulation.setObjectName(_fromUtf8("toolBar_Emulation"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_Emulation)
        self.dockWidget_Console = QtGui.QDockWidget(MainWindow)
        self.dockWidget_Console.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockWidget_Console.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_Console.setObjectName(_fromUtf8("dockWidget_Console"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.dockWidgetContents_5)
        self.vboxlayout1.setSpacing(0)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.textEditConsole = QtGui.QTextEdit(self.dockWidgetContents_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditConsole.sizePolicy().hasHeightForWidth())
        self.textEditConsole.setSizePolicy(sizePolicy)
        self.textEditConsole.setObjectName(_fromUtf8("textEditConsole"))
        self.vboxlayout1.addWidget(self.textEditConsole)
        self.dockWidget_Console.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_Console)
        self.toolBar_drawing = QtGui.QToolBar(MainWindow)
        self.toolBar_drawing.setIconSize(QtCore.QSize(32, 32))
        self.toolBar_drawing.setObjectName(_fromUtf8("toolBar_drawing"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_drawing)
        self.dockWidget_UndoView = QtGui.QDockWidget(MainWindow)
        self.dockWidget_UndoView.setEnabled(True)
        self.dockWidget_UndoView.setObjectName(_fromUtf8("dockWidget_UndoView"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.UndoViewDock = QtGui.QListView(self.dockWidgetContents)
        self.UndoViewDock.setObjectName(_fromUtf8("UndoViewDock"))
        self.verticalLayout.addWidget(self.UndoViewDock)
        self.dockWidget_UndoView.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_UndoView)
        self.dockWidget_Capture = QtGui.QDockWidget(MainWindow)
        self.dockWidget_Capture.setObjectName(_fromUtf8("dockWidget_Capture"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.capturesDock = QtGui.QTreeWidget(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capturesDock.sizePolicy().hasHeightForWidth())
        self.capturesDock.setSizePolicy(sizePolicy)
        self.capturesDock.setIconSize(QtCore.QSize(24, 24))
        self.capturesDock.setRootIsDecorated(False)
        self.capturesDock.setObjectName(_fromUtf8("capturesDock"))
        self.verticalLayout_2.addWidget(self.capturesDock)
        self.dockWidget_Capture.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_Capture)
        self.dockWidget_TopoSum = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_TopoSum.sizePolicy().hasHeightForWidth())
        self.dockWidget_TopoSum.setSizePolicy(sizePolicy)
        self.dockWidget_TopoSum.setMinimumSize(QtCore.QSize(84, 109))
        self.dockWidget_TopoSum.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget_TopoSum.setObjectName(_fromUtf8("dockWidget_TopoSum"))
        self.dockWidgetContents_7 = QtGui.QWidget()
        self.dockWidgetContents_7.setObjectName(_fromUtf8("dockWidgetContents_7"))
        self.gridlayout1 = QtGui.QGridLayout(self.dockWidgetContents_7)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setSpacing(0)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.treeWidget_TopologySummary = QtGui.QTreeWidget(self.dockWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_TopologySummary.sizePolicy().hasHeightForWidth())
        self.treeWidget_TopologySummary.setSizePolicy(sizePolicy)
        self.treeWidget_TopologySummary.setObjectName(_fromUtf8("treeWidget_TopologySummary"))
        self.gridlayout1.addWidget(self.treeWidget_TopologySummary, 0, 0, 1, 1)
        self.dockWidget_TopoSum.setWidget(self.dockWidgetContents_7)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_TopoSum)
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setMenuRole(QtGui.QAction.AboutRole)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.action_Quit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/quit.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Quit.setIcon(icon1)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.action_Open = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/open.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon2)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Save = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/save.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save.setIcon(icon3)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.action_IOS_images = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/binary.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_IOS_images.setIcon(icon4)
        self.action_IOS_images.setObjectName(_fromUtf8("action_IOS_images"))
        self.action_OnlineHelp = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/help.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_OnlineHelp.setIcon(icon5)
        self.action_OnlineHelp.setObjectName(_fromUtf8("action_OnlineHelp"))
        self.action_Export = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/camera-photo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/camera-photo-hover.svg")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.action_Export.setIcon(icon6)
        self.action_Export.setObjectName(_fromUtf8("action_Export"))
        self.action_StartAll = QtGui.QAction(MainWindow)
        self.action_StartAll.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/play7-test.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/play7-test.svg")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/play2-test.svg")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/play2-test.svg")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.action_StartAll.setIcon(icon7)
        self.action_StartAll.setObjectName(_fromUtf8("action_StartAll"))
        self.action_StopAll = QtGui.QAction(MainWindow)
        self.action_StopAll.setEnabled(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/stop3-test.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/stop2-test.svg")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/stop2-test.svg")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.action_StopAll.setIcon(icon8)
        self.action_StopAll.setObjectName(_fromUtf8("action_StopAll"))
        self.action_ShowHostnames = QtGui.QAction(MainWindow)
        self.action_ShowHostnames.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/show-hostname.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ShowHostnames.setIcon(icon9)
        self.action_ShowHostnames.setObjectName(_fromUtf8("action_ShowHostnames"))
        self.action_TelnetAll = QtGui.QAction(MainWindow)
        self.action_TelnetAll.setEnabled(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/console.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_TelnetAll.setIcon(icon10)
        self.action_TelnetAll.setObjectName(_fromUtf8("action_TelnetAll"))
        self.action_SaveAs = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/save-as.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_SaveAs.setIcon(icon11)
        self.action_SaveAs.setObjectName(_fromUtf8("action_SaveAs"))
        self.action_AboutQt = QtGui.QAction(MainWindow)
        self.action_AboutQt.setMenuRole(QtGui.QAction.AboutQtRole)
        self.action_AboutQt.setObjectName(_fromUtf8("action_AboutQt"))
        self.action_ZoomIn = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/zoom-in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/zoom-in-hover.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.action_ZoomIn.setIcon(icon12)
        self.action_ZoomIn.setObjectName(_fromUtf8("action_ZoomIn"))
        self.action_ZoomOut = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/zoom-out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/zoom-out-hover.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.action_ZoomOut.setIcon(icon13)
        self.action_ZoomOut.setObjectName(_fromUtf8("action_ZoomOut"))
        self.action_ZoomReset = QtGui.QAction(MainWindow)
        self.action_ZoomReset.setObjectName(_fromUtf8("action_ZoomReset"))
        self.action_SelectAll = QtGui.QAction(MainWindow)
        self.action_SelectAll.setObjectName(_fromUtf8("action_SelectAll"))
        self.action_SelectNone = QtGui.QAction(MainWindow)
        self.action_SelectNone.setObjectName(_fromUtf8("action_SelectNone"))
        self.uiPreferencesAction = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/applications.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiPreferencesAction.setIcon(icon14)
        self.uiPreferencesAction.setObjectName(_fromUtf8("uiPreferencesAction"))
        self.action_Undo = QtGui.QAction(MainWindow)
        self.action_Undo.setEnabled(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/edit-undo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Undo.setIcon(icon15)
        self.action_Undo.setObjectName(_fromUtf8("action_Undo"))
        self.action_Redo = QtGui.QAction(MainWindow)
        self.action_Redo.setEnabled(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/edit-redo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Redo.setIcon(icon16)
        self.action_Redo.setObjectName(_fromUtf8("action_Redo"))
        self.action_SuspendAll = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/pause3-test.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/pause2-test.svg")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/pause2-test.svg")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.action_SuspendAll.setIcon(icon17)
        self.action_SuspendAll.setObjectName(_fromUtf8("action_SuspendAll"))
        self.action_Clear = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/new.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Clear.setIcon(icon18)
        self.action_Clear.setObjectName(_fromUtf8("action_Clear"))
        self.action_AddNote = QtGui.QAction(MainWindow)
        self.action_AddNote.setCheckable(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/add-note.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_AddNote.setIcon(icon19)
        self.action_AddNote.setObjectName(_fromUtf8("action_AddNote"))
        self.action_New = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/new-project.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_New.setIcon(icon20)
        self.action_New.setObjectName(_fromUtf8("action_New"))
        self.action_config = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/import_export_configs.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_config.setIcon(icon21)
        self.action_config.setObjectName(_fromUtf8("action_config"))
        self.action_InsertImage = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/image.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_InsertImage.setIcon(icon22)
        self.action_InsertImage.setObjectName(_fromUtf8("action_InsertImage"))
        self.action_Symbol_Manager = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/node_conception.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Symbol_Manager.setIcon(icon23)
        self.action_Symbol_Manager.setObjectName(_fromUtf8("action_Symbol_Manager"))
        self.action_DrawRectangle = QtGui.QAction(MainWindow)
        self.action_DrawRectangle.setCheckable(True)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/rectangle3-test.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/rectangle2-test.svg")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/rectangle2-test.svg")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.action_DrawRectangle.setIcon(icon24)
        self.action_DrawRectangle.setObjectName(_fromUtf8("action_DrawRectangle"))
        self.action_DrawEllipse = QtGui.QAction(MainWindow)
        self.action_DrawEllipse.setCheckable(True)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/ellipse3-test.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/ellipse2-test.svg")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/ellipse2-test.svg")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.action_DrawEllipse.setIcon(icon25)
        self.action_DrawEllipse.setObjectName(_fromUtf8("action_DrawEllipse"))
        self.action_ShowinterfaceNames = QtGui.QAction(MainWindow)
        self.action_ShowinterfaceNames.setCheckable(True)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/show-interface-names.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ShowinterfaceNames.setIcon(icon26)
        self.action_ShowinterfaceNames.setObjectName(_fromUtf8("action_ShowinterfaceNames"))
        self.action_Snapshot = QtGui.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/snapshot.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Snapshot.setIcon(icon27)
        self.action_Snapshot.setObjectName(_fromUtf8("action_Snapshot"))
        self.action_ShowLayers = QtGui.QAction(MainWindow)
        self.action_ShowLayers.setCheckable(True)
        self.action_ShowLayers.setObjectName(_fromUtf8("action_ShowLayers"))
        self.action_SaveProjectAs = QtGui.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/save-as-project.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_SaveProjectAs.setIcon(icon28)
        self.action_SaveProjectAs.setObjectName(_fromUtf8("action_SaveProjectAs"))
        self.action_ReloadAll = QtGui.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/reload.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ReloadAll.setIcon(icon29)
        self.action_ReloadAll.setObjectName(_fromUtf8("action_ReloadAll"))
        self.action_ConsoleAuxAll = QtGui.QAction(MainWindow)
        self.action_ConsoleAuxAll.setEnabled(True)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/aux-console.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ConsoleAuxAll.setIcon(icon30)
        self.action_ConsoleAuxAll.setObjectName(_fromUtf8("action_ConsoleAuxAll"))
        self.action_ResetInterfaceLabels = QtGui.QAction(MainWindow)
        self.action_ResetInterfaceLabels.setObjectName(_fromUtf8("action_ResetInterfaceLabels"))
        self.action_CheckForUpdate = QtGui.QAction(MainWindow)
        self.action_CheckForUpdate.setObjectName(_fromUtf8("action_CheckForUpdate"))
        self.action_ShowVirtualBoxManager = QtGui.QAction(MainWindow)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/virtualbox.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ShowVirtualBoxManager.setIcon(icon31)
        self.action_ShowVirtualBoxManager.setObjectName(_fromUtf8("action_ShowVirtualBoxManager"))
        self.action_EnergySavingStyle = QtGui.QAction(MainWindow)
        self.action_EnergySavingStyle.setCheckable(True)
        self.action_EnergySavingStyle.setObjectName(_fromUtf8("action_EnergySavingStyle"))
        self.action_DefaultStyle = QtGui.QAction(MainWindow)
        self.action_DefaultStyle.setCheckable(True)
        self.action_DefaultStyle.setChecked(True)
        self.action_DefaultStyle.setObjectName(_fromUtf8("action_DefaultStyle"))
        self.action_Router = QtGui.QAction(MainWindow)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/router.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/router-hover.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.action_Router.setIcon(icon32)
        self.action_Router.setObjectName(_fromUtf8("action_Router"))
        self.action_Switch = QtGui.QAction(MainWindow)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/switch.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon33.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/switch-hover.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.action_Switch.setIcon(icon33)
        self.action_Switch.setObjectName(_fromUtf8("action_Switch"))
        self.action_EndDevices = QtGui.QAction(MainWindow)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/PC.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon34.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/PC-hover.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.action_EndDevices.setIcon(icon34)
        self.action_EndDevices.setObjectName(_fromUtf8("action_EndDevices"))
        self.action_SecurityDevices = QtGui.QAction(MainWindow)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/firewall.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon35.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/firewall-hover.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.action_SecurityDevices.setIcon(icon35)
        self.action_SecurityDevices.setObjectName(_fromUtf8("action_SecurityDevices"))
        self.action_HighContrastStyle = QtGui.QAction(MainWindow)
        self.action_HighContrastStyle.setCheckable(True)
        self.action_HighContrastStyle.setObjectName(_fromUtf8("action_HighContrastStyle"))
        self.action_BrowseAllDevices = QtGui.QAction(MainWindow)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/browse-all-icons.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon36.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/browse-all-icons-hover.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.action_BrowseAllDevices.setIcon(icon36)
        self.action_BrowseAllDevices.setObjectName(_fromUtf8("action_BrowseAllDevices"))
        self.uiAddLinkAction = QtGui.QAction(MainWindow)
        self.uiAddLinkAction.setCheckable(True)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/connection-new.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon37.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/connection-new-hover.svg")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.uiAddLinkAction.setIcon(icon37)
        self.uiAddLinkAction.setObjectName(_fromUtf8("uiAddLinkAction"))
        self.action_Console = QtGui.QAction(MainWindow)
        self.action_Console.setIcon(icon10)
        self.action_Console.setObjectName(_fromUtf8("action_Console"))
        self.action_Export_in_a_PDF = QtGui.QAction(MainWindow)
        self.action_Export_in_a_PDF.setObjectName(_fromUtf8("action_Export_in_a_PDF"))
        self.action_Deployement_Wizard = QtGui.QAction(MainWindow)
        self.action_Deployement_Wizard.setObjectName(_fromUtf8("action_Deployement_Wizard"))
        self.action_DisableMouseWheel = QtGui.QAction(MainWindow)
        self.action_DisableMouseWheel.setCheckable(True)
        self.action_DisableMouseWheel.setObjectName(_fromUtf8("action_DisableMouseWheel"))
        self.action_ZoomUsingMouseWheel = QtGui.QAction(MainWindow)
        self.action_ZoomUsingMouseWheel.setCheckable(True)
        self.action_ZoomUsingMouseWheel.setObjectName(_fromUtf8("action_ZoomUsingMouseWheel"))
        self.action_Tips = QtGui.QAction(MainWindow)
        self.action_Tips.setObjectName(_fromUtf8("action_Tips"))
        self.action_Instructions = QtGui.QAction(MainWindow)
        self.action_Instructions.setObjectName(_fromUtf8("action_Instructions"))
        self.menu_Edit.addAction(self.action_SelectAll)
        self.menu_Edit.addAction(self.action_SelectNone)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_IOS_images)
        self.menu_Edit.addAction(self.action_Symbol_Manager)
        self.menu_Edit.addAction(self.uiPreferencesAction)
        self.menu_File.addAction(self.action_New)
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.action_SaveProjectAs)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_config)
        self.menu_File.addAction(self.action_Export)
        self.menu_File.addAction(self.action_Snapshot)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_About.addAction(self.action_OnlineHelp)
        self.menu_About.addAction(self.action_CheckForUpdate)
        self.menu_About.addAction(self.action_Instructions)
        self.menu_About.addAction(self.action_Tips)
        self.menu_About.addAction(self.action_AboutQt)
        self.menu_About.addAction(self.action_About)
        self.menuWindow_Style.addAction(self.action_DefaultStyle)
        self.menuWindow_Style.addAction(self.action_EnergySavingStyle)
        self.menu_View.addAction(self.action_ZoomIn)
        self.menu_View.addAction(self.action_ZoomOut)
        self.menu_View.addAction(self.action_ZoomReset)
        self.menu_View.addAction(self.action_ZoomUsingMouseWheel)
        self.menu_View.addAction(self.action_DisableMouseWheel)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.action_ShowLayers)
        self.menu_View.addAction(self.action_ResetInterfaceLabels)
        self.menu_View.addAction(self.action_ShowHostnames)
        self.menu_View.addAction(self.action_ShowinterfaceNames)
        self.menu_View.addAction(self.menuWindow_Style.menuAction())
        self.menuControl.addAction(self.action_StartAll)
        self.menuControl.addAction(self.action_SuspendAll)
        self.menuControl.addAction(self.action_StopAll)
        self.menuControl.addAction(self.action_ReloadAll)
        self.menuControl.addAction(self.action_ShowVirtualBoxManager)
        self.menuControl.addAction(self.action_ConsoleAuxAll)
        self.menuControl.addAction(self.action_TelnetAll)
        self.menuAnnotate.addAction(self.action_AddNote)
        self.menuAnnotate.addAction(self.action_InsertImage)
        self.menuAnnotate.addAction(self.action_DrawRectangle)
        self.menuAnnotate.addAction(self.action_DrawEllipse)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())
        self.menubar.addAction(self.menuDevice.menuAction())
        self.menubar.addAction(self.menuAnnotate.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())
        self.toolBar_General.addAction(self.action_New)
        self.toolBar_General.addAction(self.action_Open)
        self.toolBar_General.addAction(self.action_Save)
        self.toolBar_Devices.addAction(self.action_Router)
        self.toolBar_Devices.addSeparator()
        self.toolBar_Devices.addAction(self.action_Switch)
        self.toolBar_Devices.addSeparator()
        self.toolBar_Devices.addAction(self.action_EndDevices)
        self.toolBar_Devices.addSeparator()
        self.toolBar_Devices.addAction(self.action_SecurityDevices)
        self.toolBar_Devices.addSeparator()
        self.toolBar_Devices.addAction(self.action_BrowseAllDevices)
        self.toolBar_Devices.addSeparator()
        self.toolBar_Devices.addAction(self.uiAddLinkAction)
        self.toolBar_Devices.addSeparator()
        self.toolBar_Emulation.addAction(self.action_Snapshot)
        self.toolBar_Emulation.addAction(self.action_config)
        self.toolBar_Emulation.addAction(self.action_ShowinterfaceNames)
        self.toolBar_Emulation.addAction(self.action_Console)
        self.toolBar_Emulation.addSeparator()
        self.toolBar_Emulation.addAction(self.action_StartAll)
        self.toolBar_Emulation.addAction(self.action_SuspendAll)
        self.toolBar_Emulation.addAction(self.action_StopAll)
        self.toolBar_Emulation.addAction(self.action_ReloadAll)
        self.toolBar_Emulation.addAction(self.action_ShowVirtualBoxManager)
        self.toolBar_drawing.addAction(self.action_AddNote)
        self.toolBar_drawing.addAction(self.action_InsertImage)
        self.toolBar_drawing.addAction(self.action_DrawRectangle)
        self.toolBar_drawing.addAction(self.action_DrawEllipse)
        self.toolBar_drawing.addAction(self.action_ZoomIn)
        self.toolBar_drawing.addAction(self.action_ZoomOut)
        self.toolBar_drawing.addAction(self.action_Export)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.uiGraphicsView, self.uiNodesView)
        MainWindow.setTabOrder(self.uiNodesView, self.textEditConsole)
        MainWindow.setTabOrder(self.textEditConsole, self.UndoViewDock)
        MainWindow.setTabOrder(self.UndoViewDock, self.capturesDock)
        MainWindow.setTabOrder(self.capturesDock, self.treeWidget_TopologySummary)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "GNS3", None))
        self.uiGraphicsView.setStatusTip(_translate("MainWindow", "Topology Graphic View (Workspace).", None))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_About.setTitle(_translate("MainWindow", "&Help", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.menuWindow_Style.setTitle(_translate("MainWindow", "Window Style", None))
        self.menuControl.setTitle(_translate("MainWindow", "Control", None))
        self.menuAnnotate.setTitle(_translate("MainWindow", "Annotate", None))
        self.menuDevice.setTitle(_translate("MainWindow", "Device", None))
        self.menu_Tools.setTitle(_translate("MainWindow", "&Tools", None))
        self.toolBar_General.setWindowTitle(_translate("MainWindow", "General", None))
        self.uiNodesDockWidget.setWindowTitle(_translate("MainWindow", "Node Types", None))
        self.uiNodesView.setToolTip(_translate("MainWindow", "Drag Node to Workspace (press SHIFT while dragging for multiple nodes).", None))
        self.uiNodesView.setStatusTip(_translate("MainWindow", "Available Node types are colored and can be dragged to the Workspace. Press SHIFT while dragging a device to add multiple identical nodes.", None))
        self.uiNodesView.headerItem().setText(0, _translate("MainWindow", "1", None))
        self.toolBar_Devices.setWindowTitle(_translate("MainWindow", "Devices", None))
        self.toolBar_Emulation.setWindowTitle(_translate("MainWindow", "Emulation", None))
        self.dockWidget_Console.setWindowTitle(_translate("MainWindow", "Console", None))
        self.textEditConsole.setStatusTip(_translate("MainWindow", "GNS3 Management Console. Right-click for edit options. Type help for command line help.", None))
        self.toolBar_drawing.setWindowTitle(_translate("MainWindow", "Drawing", None))
        self.dockWidget_UndoView.setWindowTitle(_translate("MainWindow", "Undo Stack", None))
        self.UndoViewDock.setToolTip(_translate("MainWindow", "Click on timepoint to restore device/link history to that timepoint.", None))
        self.UndoViewDock.setStatusTip(_translate("MainWindow", "Undo stack holds device and link creation/deletion history. Click on timepoint to restore device/link history to that timepoint.", None))
        self.dockWidget_Capture.setWindowTitle(_translate("MainWindow", "Captures", None))
        self.capturesDock.setToolTip(_translate("MainWindow", "Select capture and right-click for menu.", None))
        self.capturesDock.setStatusTip(_translate("MainWindow", "Captures lists all Wireshark captures for this session. Select capture and right-click for menu.", None))
        self.capturesDock.headerItem().setText(0, _translate("MainWindow", "Hostname", None))
        self.capturesDock.headerItem().setText(1, _translate("MainWindow", "Interface", None))
        self.dockWidget_TopoSum.setWindowTitle(_translate("MainWindow", "Topology Summary", None))
        self.treeWidget_TopologySummary.setToolTip(_translate("MainWindow", "Expand device to view connections. Select link and Right-click for menu.", None))
        self.treeWidget_TopologySummary.setStatusTip(_translate("MainWindow", "Topology Summary shows device and connection status. Expand device to view connections. Select link and Right-click for menu.", None))
        self.treeWidget_TopologySummary.headerItem().setText(0, _translate("MainWindow", "1", None))
        self.action_About.setText(_translate("MainWindow", "&About", None))
        self.action_About.setStatusTip(_translate("MainWindow", "About", None))
        self.action_Quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_Quit.setStatusTip(_translate("MainWindow", "Quit", None))
        self.action_Quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_Open.setText(_translate("MainWindow", "&Open Project", None))
        self.action_Open.setToolTip(_translate("MainWindow", "Open project or topology file", None))
        self.action_Open.setStatusTip(_translate("MainWindow", "Open project or topology file", None))
        self.action_Open.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.action_Save.setText(_translate("MainWindow", "&Save project", None))
        self.action_Save.setToolTip(_translate("MainWindow", "Save project", None))
        self.action_Save.setStatusTip(_translate("MainWindow", "Save project", None))
        self.action_Save.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_IOS_images.setText(_translate("MainWindow", "IOS images and hypervisors", None))
        self.action_IOS_images.setStatusTip(_translate("MainWindow", "IOS images and hypervisors", None))
        self.action_IOS_images.setShortcut(_translate("MainWindow", "Ctrl+Shift+I", None))
        self.action_OnlineHelp.setText(_translate("MainWindow", "&Online help", None))
        self.action_OnlineHelp.setToolTip(_translate("MainWindow", "Online help", None))
        self.action_OnlineHelp.setStatusTip(_translate("MainWindow", "Online Help", None))
        self.action_Export.setText(_translate("MainWindow", "Take a screenshot", None))
        self.action_Export.setToolTip(_translate("MainWindow", "Take a screenshot", None))
        self.action_Export.setStatusTip(_translate("MainWindow", "Take a creenshot", None))
        self.action_StartAll.setText(_translate("MainWindow", "Start/Resume all devices", None))
        self.action_StartAll.setToolTip(_translate("MainWindow", "Start/Resume all devices", None))
        self.action_StartAll.setStatusTip(_translate("MainWindow", "Start/Resume all devices", None))
        self.action_StopAll.setText(_translate("MainWindow", "Stop all devices", None))
        self.action_StopAll.setToolTip(_translate("MainWindow", "Stop all devices", None))
        self.action_StopAll.setStatusTip(_translate("MainWindow", "Stop all devices", None))
        self.action_ShowHostnames.setText(_translate("MainWindow", "Show hostnames", None))
        self.action_ShowHostnames.setToolTip(_translate("MainWindow", "Show hostnames", None))
        self.action_ShowHostnames.setStatusTip(_translate("MainWindow", "Show hostnames", None))
        self.action_TelnetAll.setText(_translate("MainWindow", "Console connect to all devices", None))
        self.action_TelnetAll.setToolTip(_translate("MainWindow", "Console connect to all devices", None))
        self.action_TelnetAll.setStatusTip(_translate("MainWindow", "Console to all devices", None))
        self.action_SaveAs.setText(_translate("MainWindow", "Save topology &as…", None))
        self.action_SaveAs.setIconText(_translate("MainWindow", "Save As", None))
        self.action_SaveAs.setToolTip(_translate("MainWindow", "Save topology file as...", None))
        self.action_SaveAs.setStatusTip(_translate("MainWindow", "Save topology file as...", None))
        self.action_AboutQt.setText(_translate("MainWindow", "About &Qt", None))
        self.action_AboutQt.setStatusTip(_translate("MainWindow", "About Qt", None))
        self.action_ZoomIn.setText(_translate("MainWindow", "Zoom in", None))
        self.action_ZoomIn.setToolTip(_translate("MainWindow", "Zoom in", None))
        self.action_ZoomIn.setStatusTip(_translate("MainWindow", "Zoom in", None))
        self.action_ZoomIn.setShortcut(_translate("MainWindow", "Ctrl++", None))
        self.action_ZoomOut.setText(_translate("MainWindow", "Zoom out", None))
        self.action_ZoomOut.setToolTip(_translate("MainWindow", "Zoom out", None))
        self.action_ZoomOut.setStatusTip(_translate("MainWindow", "Zoom out", None))
        self.action_ZoomOut.setShortcut(_translate("MainWindow", "Ctrl+-", None))
        self.action_ZoomReset.setText(_translate("MainWindow", "Zoom 1:1", None))
        self.action_ZoomReset.setStatusTip(_translate("MainWindow", "Zoom Reset (1:1)", None))
        self.action_ZoomReset.setShortcut(_translate("MainWindow", "Ctrl+/", None))
        self.action_SelectAll.setText(_translate("MainWindow", "Select &all", None))
        self.action_SelectAll.setStatusTip(_translate("MainWindow", "Select All", None))
        self.action_SelectAll.setShortcut(_translate("MainWindow", "Ctrl+A", None))
        self.action_SelectNone.setText(_translate("MainWindow", "Select &none", None))
        self.action_SelectNone.setStatusTip(_translate("MainWindow", "Select None", None))
        self.action_SelectNone.setShortcut(_translate("MainWindow", "Ctrl+Shift+A", None))
        self.uiPreferencesAction.setText(_translate("MainWindow", "&Preferences...", None))
        self.uiPreferencesAction.setStatusTip(_translate("MainWindow", "Preferences", None))
        self.uiPreferencesAction.setShortcut(_translate("MainWindow", "Ctrl+Shift+P", None))
        self.action_Undo.setText(_translate("MainWindow", "&Undo", None))
        self.action_Undo.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.action_Redo.setText(_translate("MainWindow", "&Redo", None))
        self.action_Redo.setShortcut(_translate("MainWindow", "Ctrl+Y", None))
        self.action_SuspendAll.setText(_translate("MainWindow", "Suspend all devices", None))
        self.action_SuspendAll.setToolTip(_translate("MainWindow", "Suspend all devices", None))
        self.action_SuspendAll.setStatusTip(_translate("MainWindow", "Suspend all devices", None))
        self.action_Clear.setText(_translate("MainWindow", "New blank topology", None))
        self.action_Clear.setToolTip(_translate("MainWindow", "New blank topology", None))
        self.action_Clear.setStatusTip(_translate("MainWindow", "New blank topology", None))
        self.action_AddNote.setText(_translate("MainWindow", "Add note", None))
        self.action_AddNote.setToolTip(_translate("MainWindow", "Add a note", None))
        self.action_AddNote.setStatusTip(_translate("MainWindow", "Add a note", None))
        self.action_New.setText(_translate("MainWindow", "&New blank project", None))
        self.action_New.setIconText(_translate("MainWindow", "New Project", None))
        self.action_New.setToolTip(_translate("MainWindow", "New blank project", None))
        self.action_New.setStatusTip(_translate("MainWindow", "New blank project", None))
        self.action_New.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.action_config.setText(_translate("MainWindow", "&Import/Export IOS Startup Configs", None))
        self.action_config.setToolTip(_translate("MainWindow", "Import/Export IOS Startup Configs", None))
        self.action_config.setStatusTip(_translate("MainWindow", "Import/Export IOS Startup Configs", None))
        self.action_InsertImage.setText(_translate("MainWindow", "Insert picture", None))
        self.action_InsertImage.setToolTip(_translate("MainWindow", "Insert a picture", None))
        self.action_InsertImage.setStatusTip(_translate("MainWindow", "Insert a picture", None))
        self.action_Symbol_Manager.setText(_translate("MainWindow", "&Symbol manager", None))
        self.action_Symbol_Manager.setToolTip(_translate("MainWindow", "Symbol manager", None))
        self.action_Symbol_Manager.setStatusTip(_translate("MainWindow", "Symbol Manager", None))
        self.action_Symbol_Manager.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.action_DrawRectangle.setText(_translate("MainWindow", "Draw rectangle", None))
        self.action_DrawRectangle.setToolTip(_translate("MainWindow", "Draw a rectangle", None))
        self.action_DrawRectangle.setStatusTip(_translate("MainWindow", "Draw a rectangle", None))
        self.action_DrawEllipse.setText(_translate("MainWindow", "Draw ellipse", None))
        self.action_DrawEllipse.setToolTip(_translate("MainWindow", "Draw an ellipse", None))
        self.action_DrawEllipse.setStatusTip(_translate("MainWindow", "Draw an ellipse", None))
        self.action_ShowinterfaceNames.setText(_translate("MainWindow", "Show/Hide interface labels", None))
        self.action_ShowinterfaceNames.setToolTip(_translate("MainWindow", "Show/Hide interface labels", None))
        self.action_ShowinterfaceNames.setStatusTip(_translate("MainWindow", "Show/Hide interface labels", None))
        self.action_Snapshot.setText(_translate("MainWindow", "Manage snapshots", None))
        self.action_Snapshot.setToolTip(_translate("MainWindow", "Manage snapshots", None))
        self.action_Snapshot.setStatusTip(_translate("MainWindow", "Manage snapshots", None))
        self.action_ShowLayers.setText(_translate("MainWindow", "Show layers", None))
        self.action_ShowLayers.setStatusTip(_translate("MainWindow", "Show layers", None))
        self.action_SaveProjectAs.setText(_translate("MainWindow", "&Save project as…", None))
        self.action_SaveProjectAs.setToolTip(_translate("MainWindow", "Save project as...", None))
        self.action_SaveProjectAs.setStatusTip(_translate("MainWindow", "Save project as...", None))
        self.action_ReloadAll.setText(_translate("MainWindow", "Reload all devices", None))
        self.action_ReloadAll.setToolTip(_translate("MainWindow", "Reload all devices", None))
        self.action_ReloadAll.setStatusTip(_translate("MainWindow", "Reload all devices", None))
        self.action_ConsoleAuxAll.setText(_translate("MainWindow", "Console connect via AUX to all devices", None))
        self.action_ConsoleAuxAll.setToolTip(_translate("MainWindow", "Console connect via AUX to all devices", None))
        self.action_ConsoleAuxAll.setStatusTip(_translate("MainWindow", "Console AUX to all devices", None))
        self.action_ResetInterfaceLabels.setText(_translate("MainWindow", "Reset interface labels", None))
        self.action_ResetInterfaceLabels.setToolTip(_translate("MainWindow", "Reset interface labels", None))
        self.action_ResetInterfaceLabels.setStatusTip(_translate("MainWindow", "Reset Interface Labels", None))
        self.action_CheckForUpdate.setText(_translate("MainWindow", "Check for Update", None))
        self.action_CheckForUpdate.setStatusTip(_translate("MainWindow", "Check for Update", None))
        self.action_ShowVirtualBoxManager.setText(_translate("MainWindow", "Show VirtualBox Manager", None))
        self.action_ShowVirtualBoxManager.setToolTip(_translate("MainWindow", "Show VirtualBox Manager", None))
        self.action_ShowVirtualBoxManager.setStatusTip(_translate("MainWindow", "Show VirtualBox Manager", None))
        self.action_EnergySavingStyle.setText(_translate("MainWindow", "Energy Saving", None))
        self.action_EnergySavingStyle.setStatusTip(_translate("MainWindow", "Energy Saving Mode", None))
        self.action_DefaultStyle.setText(_translate("MainWindow", "Default", None))
        self.action_Router.setText(_translate("MainWindow", "Browse Routers", None))
        self.action_Router.setIconText(_translate("MainWindow", "Browse Routers", None))
        self.action_Router.setToolTip(_translate("MainWindow", "Browse Routers", None))
        self.action_Router.setStatusTip(_translate("MainWindow", "Browse Routers", None))
        self.action_Switch.setText(_translate("MainWindow", "Browse Switches", None))
        self.action_Switch.setIconText(_translate("MainWindow", "Browse Switches", None))
        self.action_Switch.setToolTip(_translate("MainWindow", "Browse Switches", None))
        self.action_Switch.setStatusTip(_translate("MainWindow", "Browse Switches", None))
        self.action_EndDevices.setText(_translate("MainWindow", "Browse End Devices", None))
        self.action_EndDevices.setIconText(_translate("MainWindow", "Browse End Devices", None))
        self.action_EndDevices.setToolTip(_translate("MainWindow", "Browse End Devices", None))
        self.action_EndDevices.setStatusTip(_translate("MainWindow", "Browse End Devices", None))
        self.action_SecurityDevices.setText(_translate("MainWindow", "Browse Security Devices", None))
        self.action_SecurityDevices.setIconText(_translate("MainWindow", "Browse Security Devices", None))
        self.action_SecurityDevices.setToolTip(_translate("MainWindow", "Browse Security Devices", None))
        self.action_SecurityDevices.setStatusTip(_translate("MainWindow", "Browse Security Devices", None))
        self.action_HighContrastStyle.setText(_translate("MainWindow", "High Contrast", None))
        self.action_HighContrastStyle.setStatusTip(_translate("MainWindow", "High Contrast Mode", None))
        self.action_BrowseAllDevices.setText(_translate("MainWindow", "Browse all devices", None))
        self.action_BrowseAllDevices.setToolTip(_translate("MainWindow", "Browse all devices", None))
        self.action_BrowseAllDevices.setStatusTip(_translate("MainWindow", "Browse all devices", None))
        self.uiAddLinkAction.setText(_translate("MainWindow", "Add a link", None))
        self.uiAddLinkAction.setToolTip(_translate("MainWindow", "Add a link", None))
        self.uiAddLinkAction.setStatusTip(_translate("MainWindow", "Add a link", None))
        self.action_Console.setText(_translate("MainWindow", "Console", None))
        self.action_Console.setToolTip(_translate("MainWindow", "Start Console...", None))
        self.action_Console.setStatusTip(_translate("MainWindow", "Start Console...", None))
        self.action_Export_in_a_PDF.setText(_translate("MainWindow", "Export in a PDF", None))
        self.action_Deployement_Wizard.setText(_translate("MainWindow", "Deployement Wizard", None))
        self.action_DisableMouseWheel.setText(_translate("MainWindow", "Disable Mouse Wheel", None))
        self.action_DisableMouseWheel.setToolTip(_translate("MainWindow", "Disable Mouse Wheel", None))
        self.action_ZoomUsingMouseWheel.setText(_translate("MainWindow", "Zoom using Mouse Wheel", None))
        self.action_ZoomUsingMouseWheel.setToolTip(_translate("MainWindow", "Zoom in/out using the mouse whee", None))
        self.action_Tips.setText(_translate("MainWindow", "Tips", None))
        self.action_Tips.setToolTip(_translate("MainWindow", "Show Tips", None))
        self.action_Instructions.setText(_translate("MainWindow", "Instructions", None))

from ..nodes_view import NodesView
from ..graphics_view import GraphicsView
from . import resources_rc
