# Form implementation generated from reading ui file '/home/grossmj/PycharmProjects/gns3-gui/gns3/ui/password_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PasswordDialog(object):
    def setupUi(self, PasswordDialog):
        PasswordDialog.setObjectName("PasswordDialog")
        PasswordDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        PasswordDialog.resize(377, 111)
        PasswordDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(PasswordDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.uiConfirmPasswordLineEdit = QtWidgets.QLineEdit(parent=PasswordDialog)
        self.uiConfirmPasswordLineEdit.setMaxLength(100)
        self.uiConfirmPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.uiConfirmPasswordLineEdit.setObjectName("uiConfirmPasswordLineEdit")
        self.gridLayout.addWidget(self.uiConfirmPasswordLineEdit, 1, 1, 1, 1)
        self.uiPasswordLabel = QtWidgets.QLabel(parent=PasswordDialog)
        self.uiPasswordLabel.setObjectName("uiPasswordLabel")
        self.gridLayout.addWidget(self.uiPasswordLabel, 0, 0, 1, 1)
        self.uiPasswordLineEdit = QtWidgets.QLineEdit(parent=PasswordDialog)
        self.uiPasswordLineEdit.setMaxLength(100)
        self.uiPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.uiPasswordLineEdit.setObjectName("uiPasswordLineEdit")
        self.gridLayout.addWidget(self.uiPasswordLineEdit, 0, 1, 1, 1)
        self.uiConfirmPasswordLabel = QtWidgets.QLabel(parent=PasswordDialog)
        self.uiConfirmPasswordLabel.setObjectName("uiConfirmPasswordLabel")
        self.gridLayout.addWidget(self.uiConfirmPasswordLabel, 1, 0, 1, 1)
        self.uiButtonBox = QtWidgets.QDialogButtonBox(parent=PasswordDialog)
        self.uiButtonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.uiButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.uiButtonBox.setObjectName("uiButtonBox")
        self.gridLayout.addWidget(self.uiButtonBox, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)

        self.retranslateUi(PasswordDialog)
        self.uiButtonBox.accepted.connect(PasswordDialog.accept) # type: ignore
        self.uiButtonBox.rejected.connect(PasswordDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PasswordDialog)
        PasswordDialog.setTabOrder(self.uiPasswordLineEdit, self.uiConfirmPasswordLineEdit)

    def retranslateUi(self, PasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        PasswordDialog.setWindowTitle(_translate("PasswordDialog", "Change password"))
        self.uiPasswordLabel.setText(_translate("PasswordDialog", "New password:"))
        self.uiConfirmPasswordLabel.setText(_translate("PasswordDialog", "Confirm password:"))
