# Form implementation generated from reading ui file '/home/grossmj/PycharmProjects/gns3-gui/gns3/ui/symbol_selection_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SymbolSelectionDialog(object):
    def setupUi(self, SymbolSelectionDialog):
        SymbolSelectionDialog.setObjectName("SymbolSelectionDialog")
        SymbolSelectionDialog.resize(610, 700)
        SymbolSelectionDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SymbolSelectionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uiCustomSymbolRadioButton = QtWidgets.QRadioButton(parent=SymbolSelectionDialog)
        self.uiCustomSymbolRadioButton.setChecked(True)
        self.uiCustomSymbolRadioButton.setObjectName("uiCustomSymbolRadioButton")
        self.horizontalLayout_2.addWidget(self.uiCustomSymbolRadioButton)
        self.uiBuiltInSymbolRadioButton = QtWidgets.QRadioButton(parent=SymbolSelectionDialog)
        self.uiBuiltInSymbolRadioButton.setObjectName("uiBuiltInSymbolRadioButton")
        self.horizontalLayout_2.addWidget(self.uiBuiltInSymbolRadioButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.uiCustomSymbolGroupBox = QtWidgets.QGroupBox(parent=SymbolSelectionDialog)
        self.uiCustomSymbolGroupBox.setObjectName("uiCustomSymbolGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.uiCustomSymbolGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.uiSymbolToolButton = QtWidgets.QToolButton(parent=self.uiCustomSymbolGroupBox)
        self.uiSymbolToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextOnly)
        self.uiSymbolToolButton.setObjectName("uiSymbolToolButton")
        self.gridLayout.addWidget(self.uiSymbolToolButton, 0, 2, 1, 1)
        self.uiSymbolLineEdit = QtWidgets.QLineEdit(parent=self.uiCustomSymbolGroupBox)
        self.uiSymbolLineEdit.setObjectName("uiSymbolLineEdit")
        self.gridLayout.addWidget(self.uiSymbolLineEdit, 0, 1, 1, 1)
        self.uiSymbolLabel = QtWidgets.QLabel(parent=self.uiCustomSymbolGroupBox)
        self.uiSymbolLabel.setObjectName("uiSymbolLabel")
        self.gridLayout.addWidget(self.uiSymbolLabel, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.uiCustomSymbolGroupBox)
        self.uiBuiltInGroupBox = QtWidgets.QGroupBox(parent=SymbolSelectionDialog)
        self.uiBuiltInGroupBox.setObjectName("uiBuiltInGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.uiBuiltInGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.uiSymbolTreeWidget = QtWidgets.QTreeWidget(parent=self.uiBuiltInGroupBox)
        self.uiSymbolTreeWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.uiSymbolTreeWidget.setIndentation(10)
        self.uiSymbolTreeWidget.setObjectName("uiSymbolTreeWidget")
        self.uiSymbolTreeWidget.headerItem().setText(0, "1")
        self.uiSymbolTreeWidget.header().setVisible(False)
        self.gridLayout_2.addWidget(self.uiSymbolTreeWidget, 1, 0, 1, 2)
        self.uiSearchLineEdit = QtWidgets.QLineEdit(parent=self.uiBuiltInGroupBox)
        self.uiSearchLineEdit.setObjectName("uiSearchLineEdit")
        self.gridLayout_2.addWidget(self.uiSearchLineEdit, 0, 1, 1, 1)
        self.uiSearchLabel = QtWidgets.QLabel(parent=self.uiBuiltInGroupBox)
        self.uiSearchLabel.setObjectName("uiSearchLabel")
        self.gridLayout_2.addWidget(self.uiSearchLabel, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.uiBuiltInGroupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.uiButtonBox = QtWidgets.QDialogButtonBox(parent=SymbolSelectionDialog)
        self.uiButtonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.uiButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.uiButtonBox.setObjectName("uiButtonBox")
        self.horizontalLayout.addWidget(self.uiButtonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.uiBuiltInGroupBox.raise_()
        self.uiCustomSymbolGroupBox.raise_()

        self.retranslateUi(SymbolSelectionDialog)
        self.uiButtonBox.accepted.connect(SymbolSelectionDialog.accept) # type: ignore
        self.uiButtonBox.rejected.connect(SymbolSelectionDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SymbolSelectionDialog)

    def retranslateUi(self, SymbolSelectionDialog):
        _translate = QtCore.QCoreApplication.translate
        SymbolSelectionDialog.setWindowTitle(_translate("SymbolSelectionDialog", "Symbol selection"))
        self.uiCustomSymbolRadioButton.setText(_translate("SymbolSelectionDialog", "Use a custom symbol"))
        self.uiBuiltInSymbolRadioButton.setText(_translate("SymbolSelectionDialog", "Symbols library"))
        self.uiCustomSymbolGroupBox.setTitle(_translate("SymbolSelectionDialog", "Custom symbol"))
        self.uiSymbolToolButton.setText(_translate("SymbolSelectionDialog", "&Browse..."))
        self.uiSymbolLabel.setText(_translate("SymbolSelectionDialog", "Path:"))
        self.uiBuiltInGroupBox.setTitle(_translate("SymbolSelectionDialog", "Symbols"))
        self.uiSearchLabel.setText(_translate("SymbolSelectionDialog", "Filter:"))
