# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/noplay/code/gns3/gns3-gui/gns3/modules/qemu/ui/qemu_vm_wizard.ui'
#
# Created: Fri Apr 17 10:44:35 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from gns3.qt import QtCore, QtGui, QtWidgets


class Ui_QemuVMWizard:

    def setupUi(self, QemuVMWizard):
        QemuVMWizard.setObjectName("QemuVMWizard")
        QemuVMWizard.resize(514, 366)
        QemuVMWizard.setModal(True)
        self.uiServerWizardPage = QtWidgets.QWizardPage()
        self.uiServerWizardPage.setObjectName("uiServerWizardPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.uiServerWizardPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.uiServerTypeGroupBox = QtWidgets.QGroupBox(self.uiServerWizardPage)
        self.uiServerTypeGroupBox.setObjectName("uiServerTypeGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.uiServerTypeGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiRemoteRadioButton = QtWidgets.QRadioButton(self.uiServerTypeGroupBox)
        self.uiRemoteRadioButton.setChecked(True)
        self.uiRemoteRadioButton.setObjectName("uiRemoteRadioButton")
        self.horizontalLayout.addWidget(self.uiRemoteRadioButton)
        self.uiCloudRadioButton = QtWidgets.QRadioButton(self.uiServerTypeGroupBox)
        self.uiCloudRadioButton.setObjectName("uiCloudRadioButton")
        self.horizontalLayout.addWidget(self.uiCloudRadioButton)
        self.uiLocalRadioButton = QtWidgets.QRadioButton(self.uiServerTypeGroupBox)
        self.uiLocalRadioButton.setObjectName("uiLocalRadioButton")
        self.horizontalLayout.addWidget(self.uiLocalRadioButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_4.addWidget(self.uiServerTypeGroupBox, 0, 0, 1, 1)
        self.uiRemoteServersGroupBox = QtWidgets.QGroupBox(self.uiServerWizardPage)
        self.uiRemoteServersGroupBox.setObjectName("uiRemoteServersGroupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.uiRemoteServersGroupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.uiRemoteServersComboBox = QtWidgets.QComboBox(self.uiRemoteServersGroupBox)
        self.uiRemoteServersComboBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiRemoteServersComboBox.sizePolicy().hasHeightForWidth())
        self.uiRemoteServersComboBox.setSizePolicy(sizePolicy)
        self.uiRemoteServersComboBox.setObjectName("uiRemoteServersComboBox")
        self.gridLayout_8.addWidget(self.uiRemoteServersComboBox, 0, 1, 1, 1)
        self.uiRemoteServersLabel = QtWidgets.QLabel(self.uiRemoteServersGroupBox)
        self.uiRemoteServersLabel.setObjectName("uiRemoteServersLabel")
        self.gridLayout_8.addWidget(self.uiRemoteServersLabel, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.uiRemoteServersGroupBox, 1, 0, 1, 1)
        QemuVMWizard.addPage(self.uiServerWizardPage)
        self.uiTypeWizardPage = QtWidgets.QWizardPage()
        self.uiTypeWizardPage.setObjectName("uiTypeWizardPage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.uiTypeWizardPage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uiTypeLabel = QtWidgets.QLabel(self.uiTypeWizardPage)
        self.uiTypeLabel.setObjectName("uiTypeLabel")
        self.horizontalLayout_2.addWidget(self.uiTypeLabel)
        self.uiTypeComboBox = QtWidgets.QComboBox(self.uiTypeWizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiTypeComboBox.sizePolicy().hasHeightForWidth())
        self.uiTypeComboBox.setSizePolicy(sizePolicy)
        self.uiTypeComboBox.setObjectName("uiTypeComboBox")
        self.horizontalLayout_2.addWidget(self.uiTypeComboBox)
        QemuVMWizard.addPage(self.uiTypeWizardPage)
        self.uiNameWizardPage = QtWidgets.QWizardPage()
        self.uiNameWizardPage.setObjectName("uiNameWizardPage")
        self.gridLayout = QtWidgets.QGridLayout(self.uiNameWizardPage)
        self.gridLayout.setObjectName("gridLayout")
        self.uiNameLineEdit = QtWidgets.QLineEdit(self.uiNameWizardPage)
        self.uiNameLineEdit.setObjectName("uiNameLineEdit")
        self.gridLayout.addWidget(self.uiNameLineEdit, 0, 1, 1, 1)
        self.uiNameLabel = QtWidgets.QLabel(self.uiNameWizardPage)
        self.uiNameLabel.setObjectName("uiNameLabel")
        self.gridLayout.addWidget(self.uiNameLabel, 0, 0, 1, 1)
        QemuVMWizard.addPage(self.uiNameWizardPage)
        self.uiBinaryMemoryWizardPage = QtWidgets.QWizardPage()
        self.uiBinaryMemoryWizardPage.setObjectName("uiBinaryMemoryWizardPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.uiBinaryMemoryWizardPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.uiRamLabel = QtWidgets.QLabel(self.uiBinaryMemoryWizardPage)
        self.uiRamLabel.setObjectName("uiRamLabel")
        self.gridLayout_2.addWidget(self.uiRamLabel, 1, 0, 1, 1)
        self.uiQemuListLabel = QtWidgets.QLabel(self.uiBinaryMemoryWizardPage)
        self.uiQemuListLabel.setObjectName("uiQemuListLabel")
        self.gridLayout_2.addWidget(self.uiQemuListLabel, 0, 0, 1, 1)
        self.uiRamSpinBox = QtWidgets.QSpinBox(self.uiBinaryMemoryWizardPage)
        self.uiRamSpinBox.setMinimum(32)
        self.uiRamSpinBox.setMaximum(65535)
        self.uiRamSpinBox.setProperty("value", 256)
        self.uiRamSpinBox.setObjectName("uiRamSpinBox")
        self.gridLayout_2.addWidget(self.uiRamSpinBox, 1, 1, 1, 1)
        self.uiQemuListComboBox = QtWidgets.QComboBox(self.uiBinaryMemoryWizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiQemuListComboBox.sizePolicy().hasHeightForWidth())
        self.uiQemuListComboBox.setSizePolicy(sizePolicy)
        self.uiQemuListComboBox.setObjectName("uiQemuListComboBox")
        self.gridLayout_2.addWidget(self.uiQemuListComboBox, 0, 1, 1, 1)
        QemuVMWizard.addPage(self.uiBinaryMemoryWizardPage)
        self.uiDiskWizardPage = QtWidgets.QWizardPage()
        self.uiDiskWizardPage.setObjectName("uiDiskWizardPage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.uiDiskWizardPage)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.uiHdaDiskImageLineEdit = QtWidgets.QLineEdit(self.uiDiskWizardPage)
        self.uiHdaDiskImageLineEdit.setObjectName("uiHdaDiskImageLineEdit")
        self.horizontalLayout_8.addWidget(self.uiHdaDiskImageLineEdit)
        self.uiHdaDiskImageToolButton = QtWidgets.QToolButton(self.uiDiskWizardPage)
        self.uiHdaDiskImageToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.uiHdaDiskImageToolButton.setObjectName("uiHdaDiskImageToolButton")
        self.horizontalLayout_8.addWidget(self.uiHdaDiskImageToolButton)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 0, 1, 1, 1)
        self.uiHdaDiskImageLabel = QtWidgets.QLabel(self.uiDiskWizardPage)
        self.uiHdaDiskImageLabel.setObjectName("uiHdaDiskImageLabel")
        self.gridLayout_6.addWidget(self.uiHdaDiskImageLabel, 0, 0, 1, 1)
        QemuVMWizard.addPage(self.uiDiskWizardPage)
        self.uiASAWizardPage = QtWidgets.QWizardPage()
        self.uiASAWizardPage.setObjectName("uiASAWizardPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.uiASAWizardPage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.uiLinuxBootGroupBox = QtWidgets.QGroupBox(self.uiASAWizardPage)
        self.uiLinuxBootGroupBox.setObjectName("uiLinuxBootGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.uiLinuxBootGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.uiKernelImageLineEdit = QtWidgets.QLineEdit(self.uiLinuxBootGroupBox)
        self.uiKernelImageLineEdit.setObjectName("uiKernelImageLineEdit")
        self.gridLayout_3.addWidget(self.uiKernelImageLineEdit, 1, 1, 1, 1)
        self.uiInitrdLabel = QtWidgets.QLabel(self.uiLinuxBootGroupBox)
        self.uiInitrdLabel.setObjectName("uiInitrdLabel")
        self.gridLayout_3.addWidget(self.uiInitrdLabel, 0, 0, 1, 1)
        self.uiKernelImageLabel = QtWidgets.QLabel(self.uiLinuxBootGroupBox)
        self.uiKernelImageLabel.setObjectName("uiKernelImageLabel")
        self.gridLayout_3.addWidget(self.uiKernelImageLabel, 1, 0, 1, 1)
        self.uiInitrdLineEdit = QtWidgets.QLineEdit(self.uiLinuxBootGroupBox)
        self.uiInitrdLineEdit.setObjectName("uiInitrdLineEdit")
        self.gridLayout_3.addWidget(self.uiInitrdLineEdit, 0, 1, 1, 1)
        self.uiInitrdToolButton = QtWidgets.QToolButton(self.uiLinuxBootGroupBox)
        self.uiInitrdToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.uiInitrdToolButton.setObjectName("uiInitrdToolButton")
        self.gridLayout_3.addWidget(self.uiInitrdToolButton, 0, 2, 1, 1)
        self.uiKernelImageToolButton = QtWidgets.QToolButton(self.uiLinuxBootGroupBox)
        self.uiKernelImageToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.uiKernelImageToolButton.setObjectName("uiKernelImageToolButton")
        self.gridLayout_3.addWidget(self.uiKernelImageToolButton, 1, 2, 1, 1)
        self.gridLayout_5.addWidget(self.uiLinuxBootGroupBox, 0, 0, 1, 1)
        QemuVMWizard.addPage(self.uiASAWizardPage)
        self.uiDiskImageHdbWizardPage = QtWidgets.QWizardPage()
        self.uiDiskImageHdbWizardPage.setObjectName("uiDiskImageHdbWizardPage")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.uiDiskImageHdbWizardPage)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.uiHdbDiskImageLabel = QtWidgets.QLabel(self.uiDiskImageHdbWizardPage)
        self.uiHdbDiskImageLabel.setObjectName("uiHdbDiskImageLabel")
        self.gridLayout_7.addWidget(self.uiHdbDiskImageLabel, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.uiHdbDiskImageLineEdit = QtWidgets.QLineEdit(self.uiDiskImageHdbWizardPage)
        self.uiHdbDiskImageLineEdit.setObjectName("uiHdbDiskImageLineEdit")
        self.horizontalLayout_5.addWidget(self.uiHdbDiskImageLineEdit)
        self.uiHdbDiskImageToolButton = QtWidgets.QToolButton(self.uiDiskImageHdbWizardPage)
        self.uiHdbDiskImageToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.uiHdbDiskImageToolButton.setObjectName("uiHdbDiskImageToolButton")
        self.horizontalLayout_5.addWidget(self.uiHdbDiskImageToolButton)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        QemuVMWizard.addPage(self.uiDiskImageHdbWizardPage)

        self.retranslateUi(QemuVMWizard)
        QtCore.QMetaObject.connectSlotsByName(QemuVMWizard)
        QemuVMWizard.setTabOrder(self.uiNameLineEdit, self.uiQemuListComboBox)
        QemuVMWizard.setTabOrder(self.uiQemuListComboBox, self.uiRamSpinBox)
        QemuVMWizard.setTabOrder(self.uiRamSpinBox, self.uiHdaDiskImageLineEdit)
        QemuVMWizard.setTabOrder(self.uiHdaDiskImageLineEdit, self.uiHdaDiskImageToolButton)
        QemuVMWizard.setTabOrder(self.uiHdaDiskImageToolButton, self.uiInitrdLineEdit)
        QemuVMWizard.setTabOrder(self.uiInitrdLineEdit, self.uiInitrdToolButton)
        QemuVMWizard.setTabOrder(self.uiInitrdToolButton, self.uiKernelImageLineEdit)
        QemuVMWizard.setTabOrder(self.uiKernelImageLineEdit, self.uiKernelImageToolButton)

    def retranslateUi(self, QemuVMWizard):
        _translate = QtCore.QCoreApplication.translate
        QemuVMWizard.setWindowTitle(_translate("QemuVMWizard", "New QEMU VM template"))
        self.uiServerWizardPage.setTitle(_translate("QemuVMWizard", "Server"))
        self.uiServerWizardPage.setSubTitle(_translate("QemuVMWizard", "Please choose a server type to run your new QEMU VM."))
        self.uiServerTypeGroupBox.setTitle(_translate("QemuVMWizard", "Server type"))
        self.uiRemoteRadioButton.setText(_translate("QemuVMWizard", "Remote"))
        self.uiCloudRadioButton.setText(_translate("QemuVMWizard", "Cloud"))
        self.uiLocalRadioButton.setText(_translate("QemuVMWizard", "Local"))
        self.uiRemoteServersGroupBox.setTitle(_translate("QemuVMWizard", "Remote servers"))
        self.uiRemoteServersLabel.setText(_translate("QemuVMWizard", "Run on server:"))
        self.uiTypeWizardPage.setTitle(_translate("QemuVMWizard", "QEMU VM type"))
        self.uiTypeWizardPage.setSubTitle(_translate("QemuVMWizard", "Please choose a type of QEMU VM to help with pre-configuration."))
        self.uiTypeLabel.setText(_translate("QemuVMWizard", "Type:"))
        self.uiNameWizardPage.setTitle(_translate("QemuVMWizard", "QEMU VM name"))
        self.uiNameWizardPage.setSubTitle(_translate("QemuVMWizard", "Please choose a descriptive name for your new QEMU virtual machine."))
        self.uiNameLabel.setText(_translate("QemuVMWizard", "Name:"))
        self.uiBinaryMemoryWizardPage.setTitle(_translate("QemuVMWizard", "QEMU binary and memory"))
        self.uiBinaryMemoryWizardPage.setSubTitle(_translate("QemuVMWizard", "Please check the Qemu binary is correctly set and the virtual machine has enough memory to work."))
        self.uiRamLabel.setText(_translate("QemuVMWizard", "RAM:"))
        self.uiQemuListLabel.setText(_translate("QemuVMWizard", "Qemu binary:"))
        self.uiRamSpinBox.setSuffix(_translate("QemuVMWizard", " MB"))
        self.uiDiskWizardPage.setTitle(_translate("QemuVMWizard", "Disk image"))
        self.uiDiskWizardPage.setSubTitle(_translate("QemuVMWizard", "Please choose a base disk image for your virtual machine."))
        self.uiHdaDiskImageToolButton.setText(_translate("QemuVMWizard", "&Browse..."))
        self.uiHdaDiskImageLabel.setText(_translate("QemuVMWizard", "Disk image (hda):"))
        self.uiASAWizardPage.setTitle(_translate("QemuVMWizard", "ASA VM"))
        self.uiASAWizardPage.setSubTitle(_translate("QemuVMWizard", "Please choose a initrd and a kernel image."))
        self.uiLinuxBootGroupBox.setTitle(_translate("QemuVMWizard", "Linux boot specific settings"))
        self.uiInitrdLabel.setText(_translate("QemuVMWizard", "Initial RAM disk (initrd):"))
        self.uiKernelImageLabel.setText(_translate("QemuVMWizard", "Kernel image (vmlinuz):"))
        self.uiInitrdToolButton.setText(_translate("QemuVMWizard", "&Browse..."))
        self.uiKernelImageToolButton.setText(_translate("QemuVMWizard", "&Browse..."))
        self.uiDiskImageHdbWizardPage.setTitle(_translate("QemuVMWizard", "Additional disk image"))
        self.uiDiskImageHdbWizardPage.setSubTitle(_translate("QemuVMWizard", "Please add an additional disk image for IDS."))
        self.uiHdbDiskImageLabel.setText(_translate("QemuVMWizard", "Disk image (hdb):"))
        self.uiHdbDiskImageToolButton.setText(_translate("QemuVMWizard", "&Browse..."))
