# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/grossmj/PycharmProjects/gns3-gui/gns3/modules/qemu/ui/qemu_vm_preferences_page.ui'
#
# Created: Mon Sep 22 20:39:34 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QemuVMPreferencesPageWidget(object):
    def setupUi(self, QemuVMPreferencesPageWidget):
        QemuVMPreferencesPageWidget.setObjectName(_fromUtf8("QemuVMPreferencesPageWidget"))
        QemuVMPreferencesPageWidget.resize(474, 569)
        self.vboxlayout = QtGui.QVBoxLayout(QemuVMPreferencesPageWidget)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.uiTabWidget = QtGui.QTabWidget(QemuVMPreferencesPageWidget)
        self.uiTabWidget.setEnabled(True)
        self.uiTabWidget.setObjectName(_fromUtf8("uiTabWidget"))
        self.uiQemuVMTabWidget = QtGui.QWidget()
        self.uiQemuVMTabWidget.setObjectName(_fromUtf8("uiQemuVMTabWidget"))
        self.gridLayout = QtGui.QGridLayout(self.uiQemuVMTabWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.uiQemuVMsTreeWidget = QtGui.QTreeWidget(self.uiQemuVMTabWidget)
        self.uiQemuVMsTreeWidget.setObjectName(_fromUtf8("uiQemuVMsTreeWidget"))
        self.gridLayout.addWidget(self.uiQemuVMsTreeWidget, 0, 0, 1, 2)
        self.uiPreconfigurationLabel = QtGui.QLabel(self.uiQemuVMTabWidget)
        self.uiPreconfigurationLabel.setObjectName(_fromUtf8("uiPreconfigurationLabel"))
        self.gridLayout.addWidget(self.uiPreconfigurationLabel, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uiPreconfigurationComboBox = QtGui.QComboBox(self.uiQemuVMTabWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPreconfigurationComboBox.sizePolicy().hasHeightForWidth())
        self.uiPreconfigurationComboBox.setSizePolicy(sizePolicy)
        self.uiPreconfigurationComboBox.setObjectName(_fromUtf8("uiPreconfigurationComboBox"))
        self.horizontalLayout.addWidget(self.uiPreconfigurationComboBox)
        self.uiApplyPreconfigurationPushButton = QtGui.QPushButton(self.uiQemuVMTabWidget)
        self.uiApplyPreconfigurationPushButton.setObjectName(_fromUtf8("uiApplyPreconfigurationPushButton"))
        self.horizontalLayout.addWidget(self.uiApplyPreconfigurationPushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.uiQemuListLabel = QtGui.QLabel(self.uiQemuVMTabWidget)
        self.uiQemuListLabel.setObjectName(_fromUtf8("uiQemuListLabel"))
        self.gridLayout.addWidget(self.uiQemuListLabel, 2, 0, 1, 1)
        self.uiQemuListComboBox = QtGui.QComboBox(self.uiQemuVMTabWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiQemuListComboBox.sizePolicy().hasHeightForWidth())
        self.uiQemuListComboBox.setSizePolicy(sizePolicy)
        self.uiQemuListComboBox.setObjectName(_fromUtf8("uiQemuListComboBox"))
        self.gridLayout.addWidget(self.uiQemuListComboBox, 2, 1, 1, 1)
        self.uiNameLabel = QtGui.QLabel(self.uiQemuVMTabWidget)
        self.uiNameLabel.setObjectName(_fromUtf8("uiNameLabel"))
        self.gridLayout.addWidget(self.uiNameLabel, 3, 0, 1, 1)
        self.uiNameLineEdit = QtGui.QLineEdit(self.uiQemuVMTabWidget)
        self.uiNameLineEdit.setObjectName(_fromUtf8("uiNameLineEdit"))
        self.gridLayout.addWidget(self.uiNameLineEdit, 3, 1, 1, 1)
        self.uiHdaDiskImageLabel = QtGui.QLabel(self.uiQemuVMTabWidget)
        self.uiHdaDiskImageLabel.setObjectName(_fromUtf8("uiHdaDiskImageLabel"))
        self.gridLayout.addWidget(self.uiHdaDiskImageLabel, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.uiHdaDiskImageLineEdit = QtGui.QLineEdit(self.uiQemuVMTabWidget)
        self.uiHdaDiskImageLineEdit.setObjectName(_fromUtf8("uiHdaDiskImageLineEdit"))
        self.horizontalLayout_6.addWidget(self.uiHdaDiskImageLineEdit)
        self.uiHdaDiskImageToolButton = QtGui.QToolButton(self.uiQemuVMTabWidget)
        self.uiHdaDiskImageToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.uiHdaDiskImageToolButton.setObjectName(_fromUtf8("uiHdaDiskImageToolButton"))
        self.horizontalLayout_6.addWidget(self.uiHdaDiskImageToolButton)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 1, 1, 1)
        self.uiRamLabel = QtGui.QLabel(self.uiQemuVMTabWidget)
        self.uiRamLabel.setObjectName(_fromUtf8("uiRamLabel"))
        self.gridLayout.addWidget(self.uiRamLabel, 5, 0, 1, 1)
        self.uiRamSpinBox = QtGui.QSpinBox(self.uiQemuVMTabWidget)
        self.uiRamSpinBox.setMinimum(32)
        self.uiRamSpinBox.setMaximum(65535)
        self.uiRamSpinBox.setProperty("value", 256)
        self.uiRamSpinBox.setObjectName(_fromUtf8("uiRamSpinBox"))
        self.gridLayout.addWidget(self.uiRamSpinBox, 5, 1, 1, 1)
        self.uiAdaptersLabel = QtGui.QLabel(self.uiQemuVMTabWidget)
        self.uiAdaptersLabel.setObjectName(_fromUtf8("uiAdaptersLabel"))
        self.gridLayout.addWidget(self.uiAdaptersLabel, 6, 0, 1, 1)
        self.uiAdaptersSpinBox = QtGui.QSpinBox(self.uiQemuVMTabWidget)
        self.uiAdaptersSpinBox.setMinimum(1)
        self.uiAdaptersSpinBox.setMaximum(8)
        self.uiAdaptersSpinBox.setObjectName(_fromUtf8("uiAdaptersSpinBox"))
        self.gridLayout.addWidget(self.uiAdaptersSpinBox, 6, 1, 1, 1)
        self.uiAdapterTypesLabel = QtGui.QLabel(self.uiQemuVMTabWidget)
        self.uiAdapterTypesLabel.setObjectName(_fromUtf8("uiAdapterTypesLabel"))
        self.gridLayout.addWidget(self.uiAdapterTypesLabel, 7, 0, 1, 1)
        self.uiAdapterTypesComboBox = QtGui.QComboBox(self.uiQemuVMTabWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiAdapterTypesComboBox.sizePolicy().hasHeightForWidth())
        self.uiAdapterTypesComboBox.setSizePolicy(sizePolicy)
        self.uiAdapterTypesComboBox.setObjectName(_fromUtf8("uiAdapterTypesComboBox"))
        self.gridLayout.addWidget(self.uiAdapterTypesComboBox, 7, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.uiRefreshPushButton = QtGui.QPushButton(self.uiQemuVMTabWidget)
        self.uiRefreshPushButton.setObjectName(_fromUtf8("uiRefreshPushButton"))
        self.horizontalLayout_5.addWidget(self.uiRefreshPushButton)
        self.uiSaveQemuVMPushButton = QtGui.QPushButton(self.uiQemuVMTabWidget)
        self.uiSaveQemuVMPushButton.setObjectName(_fromUtf8("uiSaveQemuVMPushButton"))
        self.horizontalLayout_5.addWidget(self.uiSaveQemuVMPushButton)
        self.uiDeleteQemuVMPushButton = QtGui.QPushButton(self.uiQemuVMTabWidget)
        self.uiDeleteQemuVMPushButton.setEnabled(False)
        self.uiDeleteQemuVMPushButton.setObjectName(_fromUtf8("uiDeleteQemuVMPushButton"))
        self.horizontalLayout_5.addWidget(self.uiDeleteQemuVMPushButton)
        self.gridLayout.addLayout(self.horizontalLayout_5, 8, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.uiTabWidget.addTab(self.uiQemuVMTabWidget, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.uiLinuxBootGroupBox = QtGui.QGroupBox(self.tab)
        self.uiLinuxBootGroupBox.setObjectName(_fromUtf8("uiLinuxBootGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.uiLinuxBootGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.uiKernelImageLineEdit = QtGui.QLineEdit(self.uiLinuxBootGroupBox)
        self.uiKernelImageLineEdit.setObjectName(_fromUtf8("uiKernelImageLineEdit"))
        self.gridLayout_2.addWidget(self.uiKernelImageLineEdit, 1, 1, 1, 1)
        self.uiKernelCommandLineLabel = QtGui.QLabel(self.uiLinuxBootGroupBox)
        self.uiKernelCommandLineLabel.setObjectName(_fromUtf8("uiKernelCommandLineLabel"))
        self.gridLayout_2.addWidget(self.uiKernelCommandLineLabel, 2, 0, 1, 1)
        self.uiInitrdLabel = QtGui.QLabel(self.uiLinuxBootGroupBox)
        self.uiInitrdLabel.setObjectName(_fromUtf8("uiInitrdLabel"))
        self.gridLayout_2.addWidget(self.uiInitrdLabel, 0, 0, 1, 1)
        self.uiKernelImageLabel = QtGui.QLabel(self.uiLinuxBootGroupBox)
        self.uiKernelImageLabel.setObjectName(_fromUtf8("uiKernelImageLabel"))
        self.gridLayout_2.addWidget(self.uiKernelImageLabel, 1, 0, 1, 1)
        self.uiKernelCommandLineEdit = QtGui.QLineEdit(self.uiLinuxBootGroupBox)
        self.uiKernelCommandLineEdit.setObjectName(_fromUtf8("uiKernelCommandLineEdit"))
        self.gridLayout_2.addWidget(self.uiKernelCommandLineEdit, 2, 1, 1, 1)
        self.uiKernelCommandLineToolButton = QtGui.QToolButton(self.uiLinuxBootGroupBox)
        self.uiKernelCommandLineToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.uiKernelCommandLineToolButton.setObjectName(_fromUtf8("uiKernelCommandLineToolButton"))
        self.gridLayout_2.addWidget(self.uiKernelCommandLineToolButton, 2, 2, 1, 1)
        self.uiInitrdLineEdit = QtGui.QLineEdit(self.uiLinuxBootGroupBox)
        self.uiInitrdLineEdit.setObjectName(_fromUtf8("uiInitrdLineEdit"))
        self.gridLayout_2.addWidget(self.uiInitrdLineEdit, 0, 1, 1, 1)
        self.uiInitrdToolButton = QtGui.QToolButton(self.uiLinuxBootGroupBox)
        self.uiInitrdToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.uiInitrdToolButton.setObjectName(_fromUtf8("uiInitrdToolButton"))
        self.gridLayout_2.addWidget(self.uiInitrdToolButton, 0, 2, 1, 1)
        self.uiKernelImageToolButton = QtGui.QToolButton(self.uiLinuxBootGroupBox)
        self.uiKernelImageToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.uiKernelImageToolButton.setObjectName(_fromUtf8("uiKernelImageToolButton"))
        self.gridLayout_2.addWidget(self.uiKernelImageToolButton, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.uiLinuxBootGroupBox)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.uiHdbDiskImageLabel = QtGui.QLabel(self.groupBox)
        self.uiHdbDiskImageLabel.setObjectName(_fromUtf8("uiHdbDiskImageLabel"))
        self.gridLayout_3.addWidget(self.uiHdbDiskImageLabel, 0, 0, 1, 1)
        self.uiHdbDiskImageToolButton = QtGui.QToolButton(self.groupBox)
        self.uiHdbDiskImageToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.uiHdbDiskImageToolButton.setObjectName(_fromUtf8("uiHdbDiskImageToolButton"))
        self.gridLayout_3.addWidget(self.uiHdbDiskImageToolButton, 0, 2, 1, 1)
        self.uiQemuOptionsLabel = QtGui.QLabel(self.groupBox)
        self.uiQemuOptionsLabel.setObjectName(_fromUtf8("uiQemuOptionsLabel"))
        self.gridLayout_3.addWidget(self.uiQemuOptionsLabel, 1, 0, 1, 1)
        self.uiHdbDiskImageLineEdit = QtGui.QLineEdit(self.groupBox)
        self.uiHdbDiskImageLineEdit.setObjectName(_fromUtf8("uiHdbDiskImageLineEdit"))
        self.gridLayout_3.addWidget(self.uiHdbDiskImageLineEdit, 0, 1, 1, 1)
        self.uiQemuOptionsLineEdit = QtGui.QLineEdit(self.groupBox)
        self.uiQemuOptionsLineEdit.setObjectName(_fromUtf8("uiQemuOptionsLineEdit"))
        self.gridLayout_3.addWidget(self.uiQemuOptionsLineEdit, 1, 1, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 237, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.uiTabWidget.addTab(self.tab, _fromUtf8(""))
        self.vboxlayout.addWidget(self.uiTabWidget)

        self.retranslateUi(QemuVMPreferencesPageWidget)
        self.uiTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QemuVMPreferencesPageWidget)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiTabWidget, self.uiQemuVMsTreeWidget)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiQemuVMsTreeWidget, self.uiPreconfigurationComboBox)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiPreconfigurationComboBox, self.uiApplyPreconfigurationPushButton)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiApplyPreconfigurationPushButton, self.uiQemuListComboBox)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiQemuListComboBox, self.uiNameLineEdit)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiNameLineEdit, self.uiHdaDiskImageLineEdit)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiHdaDiskImageLineEdit, self.uiHdaDiskImageToolButton)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiHdaDiskImageToolButton, self.uiRamSpinBox)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiRamSpinBox, self.uiAdaptersSpinBox)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiAdaptersSpinBox, self.uiAdapterTypesComboBox)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiAdapterTypesComboBox, self.uiRefreshPushButton)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiRefreshPushButton, self.uiSaveQemuVMPushButton)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiSaveQemuVMPushButton, self.uiDeleteQemuVMPushButton)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiDeleteQemuVMPushButton, self.uiInitrdLineEdit)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiInitrdLineEdit, self.uiInitrdToolButton)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiInitrdToolButton, self.uiKernelImageLineEdit)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiKernelImageLineEdit, self.uiKernelImageToolButton)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiKernelImageToolButton, self.uiKernelCommandLineEdit)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiKernelCommandLineEdit, self.uiKernelCommandLineToolButton)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiKernelCommandLineToolButton, self.uiHdbDiskImageLineEdit)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiHdbDiskImageLineEdit, self.uiHdbDiskImageToolButton)
        QemuVMPreferencesPageWidget.setTabOrder(self.uiHdbDiskImageToolButton, self.uiQemuOptionsLineEdit)

    def retranslateUi(self, QemuVMPreferencesPageWidget):
        QemuVMPreferencesPageWidget.setWindowTitle(_translate("QemuVMPreferencesPageWidget", "QEMU VMs", None))
        self.uiQemuVMsTreeWidget.headerItem().setText(0, _translate("QemuVMPreferencesPageWidget", "VM", None))
        self.uiQemuVMsTreeWidget.headerItem().setText(1, _translate("QemuVMPreferencesPageWidget", "Server", None))
        self.uiPreconfigurationLabel.setText(_translate("QemuVMPreferencesPageWidget", "Preconfiguration:", None))
        self.uiApplyPreconfigurationPushButton.setText(_translate("QemuVMPreferencesPageWidget", "Apply", None))
        self.uiQemuListLabel.setText(_translate("QemuVMPreferencesPageWidget", "Qemu binary:", None))
        self.uiNameLabel.setText(_translate("QemuVMPreferencesPageWidget", "VM name:", None))
        self.uiHdaDiskImageLabel.setText(_translate("QemuVMPreferencesPageWidget", "Disk image (hda):", None))
        self.uiHdaDiskImageToolButton.setText(_translate("QemuVMPreferencesPageWidget", "...", None))
        self.uiRamLabel.setText(_translate("QemuVMPreferencesPageWidget", "RAM:", None))
        self.uiRamSpinBox.setSuffix(_translate("QemuVMPreferencesPageWidget", " MB", None))
        self.uiAdaptersLabel.setText(_translate("QemuVMPreferencesPageWidget", "Adapters:", None))
        self.uiAdapterTypesLabel.setText(_translate("QemuVMPreferencesPageWidget", "Type:", None))
        self.uiRefreshPushButton.setText(_translate("QemuVMPreferencesPageWidget", "Refresh QEMU list", None))
        self.uiSaveQemuVMPushButton.setText(_translate("QemuVMPreferencesPageWidget", "Save", None))
        self.uiDeleteQemuVMPushButton.setText(_translate("QemuVMPreferencesPageWidget", "Delete", None))
        self.uiTabWidget.setTabText(self.uiTabWidget.indexOf(self.uiQemuVMTabWidget), _translate("QemuVMPreferencesPageWidget", "QEMU VMs", None))
        self.uiLinuxBootGroupBox.setTitle(_translate("QemuVMPreferencesPageWidget", "Linux boot specific settings", None))
        self.uiKernelCommandLineLabel.setText(_translate("QemuVMPreferencesPageWidget", "Kernel command line:", None))
        self.uiInitrdLabel.setText(_translate("QemuVMPreferencesPageWidget", "Initial RAM disk (initrd):", None))
        self.uiKernelImageLabel.setText(_translate("QemuVMPreferencesPageWidget", "Kernel image:", None))
        self.uiKernelCommandLineToolButton.setText(_translate("QemuVMPreferencesPageWidget", "...", None))
        self.uiInitrdToolButton.setText(_translate("QemuVMPreferencesPageWidget", "...", None))
        self.uiKernelImageToolButton.setText(_translate("QemuVMPreferencesPageWidget", "...", None))
        self.groupBox.setTitle(_translate("QemuVMPreferencesPageWidget", "Aditional settings", None))
        self.uiHdbDiskImageLabel.setText(_translate("QemuVMPreferencesPageWidget", "Disk image (hdb):", None))
        self.uiHdbDiskImageToolButton.setText(_translate("QemuVMPreferencesPageWidget", "...", None))
        self.uiQemuOptionsLabel.setText(_translate("QemuVMPreferencesPageWidget", "Options:", None))
        self.uiTabWidget.setTabText(self.uiTabWidget.indexOf(self.tab), _translate("QemuVMPreferencesPageWidget", "Advanced QEMU VM settings", None))

